#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/akonadi/src/akonadi-1.13.0.tar.bz2"
MD5SUMLIST="84eb2e471bd6bdfe54a2a2f1d858c07d"
REQUIRES="boost mariadb postgresql shared-mime-info sqlite"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX  \
      -DCMAKE_BUILD_TYPE=Release           \
      -DINSTALL_QSQLITE_IN_QT_PREFIX=TRUE  \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

