#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://alsa.cybermirror.org/plugins/alsa-plugins-1.0.28.tar.bz2"
MD5SUMLIST="6fcbbb31e96f8ebc5fb926184a717aa4"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

