#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.de.debian.org/debian/pool/main/a/at/at_3.1.15.orig.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140810.tar.bz2"
MD5SUMLIST="f0f96db22e3a174b53ce4beeeb848839
            179a6c22d0f7d2619cba4eb794fdc1cb"
REQUIRES="server-mail"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/docdir/s/=.*/= @docdir@/' Makefile.in

./configure --docdir=/usr/share/doc/at-3.1.15 \
            --with-daemon_username=atd        \
            --with-daemon_groupname=atd       \
            SENDMAIL=/usr/sbin/sendmail
make -j1

make DESTDIR=${FAKEROOT} install

includeBootscript atd

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 17 atd
useradd -d /dev/null -c "atd daemon" -g atd -s /bin/false -u 17 atd
mkdir -p /var/spool/cron

#################
} # END OF FILE #
#################

