#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://distfiles.audacious-media-player.org/audacious-3.5.1.tar.bz2"
MD5SUMLIST="728df3e3f133782d2bb92e23fbbc6f55"
REQUIRES="gtk+3 libxml2 xorg xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

TPUT=/bin/true ./configure --prefix=/usr \
                           --with-buildstamp="BLFS"
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

