#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.gimp.org/pub/babl/0.1/babl-0.1.10.tar.bz2"
MD5SUMLIST="9e1542ab5c0b12ea3af076a9a2f02d79"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics
install -v -m644 docs/*.{css,html} ${FAKEROOT}/usr/share/gtk-doc/html/babl
install -v -m644 docs/graphics/*.{html,png,svg} ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics

#################
} # END OF FILE #
#################

