#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://launchpad.net/bzr/2.5/2.5.1/+download/bzr-2.5.1.tar.gz"
MD5SUMLIST="ac5079858364a046071000d5cdccb67b"
REQUIRES="python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e 's|man/man1|share/&|' setup.py
python setup.py build

python setup.py install --root=${FAKEROOT}

#################
} # END OF FILE #
#################

