#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.bennewitz.com/bluefish/stable/source/bluefish-2.2.6.tar.bz2"
MD5SUMLIST="f15919e6a7b012a16e6b1f49d9db2b33"
REQUIRES="gtk+2 gtk+3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/bluefish-2.2.6
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

