#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/boost/boost_1_56_0.tar.bz2"
MD5SUMLIST="a744cf167b05d72335f27c88115f211d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./bootstrap.sh --prefix=/usr
./b2 stage threading=multi link=shared

./b2 install threading=multi link=shared

#################
} # END OF FILE #
#################

