#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/cdparanoia/cdparanoia-III-10.2.src.tgz
          http://www.linuxfromscratch.org/patches/blfs/svn/cdparanoia-III-10.2-gcc_fixes-1.patch"
MD5SUMLIST="b304bbe8ab63373924a744eac9ebc652
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../cdparanoia-III-10.2-gcc_fixes-1.patch
./configure --prefix=/usr --mandir=/usr/share/man
make -j1

make DESTDIR=${FAKEROOT} install
chmod -v 755 ${FAKEROOT}/usr/lib/libcdda_*.so.0.10.2

#################
} # END OF FILE #
#################

