#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/cdrdao/cdrdao-1.2.3.tar.bz2"
MD5SUMLIST="8d15ba6280bb7ba2f4d6be31d28b3c0c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/ioctl/a #include <sys/stat.h>' dao/ScsiIf-linux.cc

./configure --prefix=/usr --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cdrdao-1.2.3
install -v -m644 README ${FAKEROOT}/usr/share/doc/cdrdao-1.2.3

#################
} # END OF FILE #
#################

