#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/cheese/3.12/cheese-3.12.2.tar.xz"
MD5SUMLIST="fab1e00717d8f3e027b9bb79299e12e8"
REQUIRES="clutter-gst2 clutter-gtk gnome-desktop gnome-video-effects gst10-plugins-bad gst10-plugins-good libcanberra librsvg udev-extras yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

