#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.4.tar.bz2"
MD5SUMLIST="b7d75b67fd3987952896d27256c7293d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-pam \
            --disable-systemd
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

