#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/clucene/clucene-core-2.3.3.4.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/clucene-2.3.3.4-contribs_lib-1.patch"
MD5SUMLIST="48d647fbd8ef8889e5a7f422c1bfda94
            dontverify"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../clucene-2.3.3.4-contribs_lib-1.patch
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_CONTRIBS_LIB=ON ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

