#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/clutter/1.18/clutter-1.18.4.tar.xz"
MD5SUMLIST="f4f37216a9278defb50b721c8f8ff583"
REQUIRES="atk cogl json-glib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/actor-offscreen-redirect/d' \
       tests/conform/Makefile.am tests/conform/Makefile.in
autoreconf -f -i

./configure --prefix=/usr --sysconfdir=/etc --enable-egl-backend
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

