#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.xemacs.org/pub/xemacs/aux/compface-1.5.2.tar.gz"
MD5SUMLIST="62f4f79c0861ad292ba3cf77b4c48319"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install
install -m755 -v xbm2xface.pl ${FAKEROOT}/usr/bin

#################
} # END OF FILE #
#################

