#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.openprinting.org/download/cups-filters/cups-filters-1.0.58.tar.xz"
MD5SUMLIST="9b6d607b4041e5ee9a8787e7585a8e9e"
REQUIRES="cups glib2 ijs lcms2 poppler qpdf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                               \
            --sysconfdir=/etc                           \
            --localstatedir=/var                        \
            --docdir=/usr/share/doc/cups-filters-1.0.58 \
            --without-rcdir                             \
            --with-gs-path=/usr/bin/gs                  \
            --with-pdftops-path=/usr/bin/gs             \
            --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

