#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.isc.org/isc/dhcp/4.3.1/dhcp-4.3.1.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140810.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/dhcp-4.3.1-client_script-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/dhcp-4.3.1-missing_ipv6-1.patch"
MD5SUMLIST="b3a42ece3c7f2cd2e74a3e12ca881d20
            179a6c22d0f7d2619cba4eb794fdc1cb
            dontverify
            dontverify"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../dhcp-4.3.1-missing_ipv6-1.patch

patch -Np1 -i ../dhcp-4.3.1-client_script-1.patch
CFLAGS="-D_PATH_DHCLIENT_SCRIPT='\"/sbin/dhclient-script\"'         \
        -D_PATH_DHCPD_CONF='\"/etc/dhcp/dhcpd.conf\"'               \
        -D_PATH_DHCLIENT_CONF='\"/etc/dhcp/dhclient.conf\"'"        \
./configure --prefix=/usr                                           \
            --sysconfdir=/etc/dhcp                                  \
            --localstatedir=/var                                    \
            --with-srv-lease-file=/var/lib/dhcpd/dhcpd.leases       \
            --with-srv6-lease-file=/var/lib/dhcpd/dhcpd6.leases     \
            --with-cli-lease-file=/var/lib/dhclient/dhclient.leases \
            --with-cli6-lease-file=/var/lib/dhclient/dhclient6.leases
make

make DESTDIR=${FAKEROOT} -C client install
mv -v ${FAKEROOT}/usr/sbin/dhclient ${FAKEROOT}/sbin
install -v -m755 client/scripts/linux ${FAKEROOT}/sbin/dhclient-script

make DESTDIR=${FAKEROOT} -C server install

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/sbin/dhclient ${FAKEROOT}/sbin
install -v -m755 client/scripts/linux ${FAKEROOT}/sbin/dhclient-script

cat > ${FAKEROOT}/etc/dhcp/dhclient.conf << "EOF"
# Begin /etc/dhcp/dhclient.conf
#
# Basic dhclient.conf(5)

#prepend domain-name-servers 127.0.0.1;
request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, domain-search, host-name,
        netbios-name-servers, netbios-scope, interface-mtu,
        ntp-servers;
require subnet-mask, domain-name-servers;
#timeout 60;
#retry 60;
#reboot 10;
#select-timeout 5;
#initial-interval 2;

# End /etc/dhcp/dhclient.conf
EOF

install -v -dm 755 ${FAKEROOT}/var/lib/dhclient

includeBootscript service-dhclient

cat > ${FAKEROOT}/etc/sysconfig/ifconfig.eth0 << "EOF"
ONBOOT="yes"
IFACE="eth0"
SERVICE="dhclient"
DHCP_START=""
DHCP_STOP=""

# Set PRINTIP="yes" to have the script print
# the DHCP assigned IP address
PRINTIP="no"

# Set PRINTALL="yes" to print the DHCP assigned values for
# IP, SM, DG, and 1st NS. This requires PRINTIP="yes".
PRINTALL="no"
EOF

cat > ${FAKEROOT}/etc/dhcp/dhcpd.conf << "EOF"
# Begin /etc/dhcp/dhcpd.conf
#
# Example dhcpd.conf(5)

# Use this to enble / disable dynamic dns updates globally.
ddns-update-style none;

# option definitions common to all supported networks...
option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;

default-lease-time 600;
max-lease-time 7200;

# This is a very basic subnet declaration.
subnet 10.254.239.0 netmask 255.255.255.224 {
  range 10.254.239.10 10.254.239.20;
  option routers rtr-239-0-1.example.org, rtr-239-0-2.example.org;
}

# End /etc/dhcp/dhcpd.conf
EOF

install -v -dm 755 ${FAKEROOT}/var/lib/dhcpd

includeBootscript dhcpd

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

dhclient <eth0>

#################
} # END OF FILE #
#################

