#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/pub/gnu/ed/ed-1.10.tar.lz"
MD5SUMLIST="d1e51bb6e78417af8fb12684c31fd9eb"
REQUIRES="libarchive"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --bindir=/bin
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

