#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/evince/3.12/evince-3.12.2.tar.xz"
MD5SUMLIST="f8ea3cb5ba39c75a0b28b34a9c508cd4"
REQUIRES="gnome-icon-theme gsettings-desktop-schemas gtk+3 yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr           \
            --enable-introspection  \
            --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

