#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/flac/flac-1.3.0.tar.xz"
MD5SUMLIST="13b5c214cee8373464d3d65dee362cdd"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-thorough-tests
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

