#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://fltk.org/pub/fltk/1.3.2/fltk-1.3.2-source.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/fltk-1.3.2-dynamic_libs-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/fltk-1.3.2-tigervnc-1.patch"
MD5SUMLIST="9f7e707d4fb7a5a76f0f9b73ff70623d
            dontverify
            dontverify"
REQUIRES="glu mesalib x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../fltk-1.3.2-tigervnc-1.patch
patch -Np1 -i ../fltk-1.3.2-dynamic_libs-1.patch
sed -i -e '/FL_PATCH_VERSION=/ s/1/2/' configure
sed -i -e '/cat./d' documentation/Makefile

./configure --prefix=/usr    \
            --enable-threads \
            --enable-xft     \
            --enable-shared
make

make -C documentation html

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc/fltk-1.3.2 install

make DESTDIR=${FAKEROOT} -C test install-linux
make DESTDIR=${FAKEROOT} -C documentation install-linux

#################
} # END OF FILE #
#################

