#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/freetts/freetts-1.2.2-src.zip
          http://downloads.sourceforge.net/freetts/freetts-1.2.2-tst.zip"
MD5SUMLIST="692b5ece251fed88539736e55af5f391
            dontverify"
REQUIRES="apache-ant sharutils"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

unzip -q freetts-1.2.2-src.zip -x META-INF/*
unzip -q freetts-1.2.2-tst.zip -x META-INF/*

sed -i 's/value="src/value="./' build.xml
cd lib
sh jsapi.sh
cd ..
ant

ant junit
cd tests
sh regression.sh
cd ..

install -v -m755 -d ${FAKEROOT}/opt/freetts-1.2.2/{lib,docs/{audio,images}}
install -v -m644 lib/*.jar ${FAKEROOT}/opt/freetts-1.2.2/lib
install -v -m644 *.txt RELEASE_NOTES docs/*.{pdf,html,txt,sx{w,d}} \
                               ${FAKEROOT}/opt/freetts-1.2.2/docs
install -v -m644 docs/audio/*  ${FAKEROOT}/opt/freetts-1.2.2/docs/audio
install -v -m644 docs/images/* ${FAKEROOT}/opt/freetts-1.2.2/docs/images
cp -v -R javadoc               ${FAKEROOT}/opt/freetts-1.2.2
ln -v -s freetts-1.2.2 ${FAKEROOT}/opt/freetts

cp -v -R bin    ${FAKEROOT}/opt/freetts-1.2.2
install -v -m644 speech.properties $JAVA_HOME/jre/lib
cp -v -R tools  ${FAKEROOT}/opt/freetts-1.2.2
cp -v -R mbrola ${FAKEROOT}/opt/freetts-1.2.2
cp -v -R demo   ${FAKEROOT}/opt/freetts-1.2.2

#################
} # END OF FILE #
#################

