#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/fuse/fuse-2.9.3.tar.gz"
MD5SUMLIST="33cae22ca50311446400daf8a6255c6a"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static INIT_D_PATH=/tmp/init.d
make

make DESTDIR=${FAKEROOT} install

mv -v   ${FAKEROOT}/usr/lib/libfuse.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/libfuse.so.2.9.3 ${FAKEROOT}/usr/lib/libfuse.so
rm -rf  ${FAKEROOT}/tmp/init.d

install -v -m755 -d ${FAKEROOT}/usr/share/doc/fuse-2.9.3
install -v -m644    doc/{how-fuse-works,kernel.txt} \
                    ${FAKEROOT}/usr/share/doc/fuse-2.9.3

install -v -m755 -d ${FAKEROOT}/usr/share/doc/fuse-2.9.3/api
install -v -m644    doc/html/* \
                    ${FAKEROOT}/usr/share/doc/fuse-2.9.3/api

cat > ${FAKEROOT}/etc/fuse.conf << "EOF"
# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#
#mount_max = 1000

# Allow non-root users to specify the 'allow_other' or 'allow_root'
# mount options.
#
#user_allow_other
EOF

#################
} # END OF FILE #
#################

