#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/gdb/gdb-7.8.tar.xz"
MD5SUMLIST="bd958fe9019d7c7896f29f6724a764ed"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-system-readline
make

make DESTDIR=${FAKEROOT} -C gdb install

#################
} # END OF FILE #
#################

