#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="apr apr-util aspell boost clucene dbus-glib enchant exempi glib2 glibmm gmime gobject-introspection grantlee gsl icu js js2 json-c json-glib keyutils libarchive libassuan libatasmart libatomic_ops libcroco libdaemon libdbusmenuqt libesmtp libffi libgcrypt libgee libgpg-error libgsf libgusb libical libidn libiodbc libksba liblinear libsigc++ libtasn1 libunistring libusb libusb-compat libxml2 libxslt libzeitgeist lzo mtdev nspr openobex pcre popt pth ptlib qca qjson talloc wv xapian"
TAGS="group"

