#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="acpid at autofs colord cpio dbus fcron gpm hdparm initdtools lm_sensors logrotate mc obex-data-server p7zip pax pciutils pm-utils raptor rasqal redland sg3_utils strigi sysstat udev-extras udisks udisks2 unrar unzip upower usbutils which zip"
TAGS="group"

