#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://launchpad.net/geoclue/trunk/0.12/+download/geoclue-0.12.0.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/geoclue-0.12.0-gpsd_fix-1.patch"
MD5SUMLIST="33af8307f332e0065af056ecba65fec2
            dontverify"
REQUIRES="dbus-glib gconf libxslt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../geoclue-0.12.0-gpsd_fix-1.patch
sed -i "s@ -Werror@@" configure
sed -i "s@libnm_glib@libnm-glib@g" configure
sed -i "s@geoclue/libgeoclue.la@& -lgthread-2.0@g" \
       providers/skyhook/Makefile.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

