#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/giflib/giflib-5.1.0.tar.bz2"
MD5SUMLIST="c7e9f1c10b755ab955156d4c1ac7fc5d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -dm755           ${FAKEROOT}/usr/share/doc/giflib-5.1.0/html
install -v -m644 doc/*.html ${FAKEROOT}/usr/share/doc/giflib-5.1.0/html

#################
} # END OF FILE #
#################

