#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://www.kernel.org/pub/software/scm/git/git-2.1.0.tar.xz
          https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.1.0.tar.xz
          https://www.kernel.org/pub/software/scm/git/git-manpages-2.1.0.tar.xz"
MD5SUMLIST="47b1f55d9a16be112f7ae2c778a9b30c
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr         \
            --with-gitconfig=/etc/gitconfig
make

make html

make man

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install-man

make DESTDIR=${FAKEROOT} htmldir=/usr/share/doc/git-2.1.0 install-html

tar -xf ../git-manpages-2.1.0.tar.xz -C ${FAKEROOT}/usr/share/man --no-same-owner --no-overwrite-dir

mkdir -p ${FAKEROOT}/usr/share/doc/git-2.1.0/man-pages/{html,text}

tar -xf  ../git-htmldocs-2.1.0.tar.xz \
    -C   ${FAKEROOT}/usr/share/doc/git-2.1.0 --no-same-owner --no-overwrite-dir

find ${FAKEROOT}/usr/share/doc/git-2.1.0 -type d -exec chmod 755 {} \;
find ${FAKEROOT}/usr/share/doc/git-2.1.0 -type f -exec chmod 644 {} \;

mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/{git*.txt,man-pages/text}
mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/{git*.,index.,man-pages/}html
mkdir    ${FAKEROOT}/usr/share/doc/git-2.1.0/technical/{html,text}
mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/technical/{*.txt,text}
mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/technical/{*.,}html
mkdir    ${FAKEROOT}/usr/share/doc/git-2.1.0/howto/{html,text}
mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/howto/{*.txt,text}
mv       ${FAKEROOT}/usr/share/doc/git-2.1.0/howto/{*.,}html

#################
} # END OF FILE #
#################

