#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-desktop/3.12/gnome-desktop-3.12.2.tar.xz"
MD5SUMLIST="9f1dd733a19e0bc4e5b923771f826509"
REQUIRES="gsettings-desktop-schemas gtk+3 iso-codes xkeyboard-config yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

