#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-terminal/3.12/gnome-terminal-3.12.3.tar.xz"
MD5SUMLIST="a3fe2df34f57e8ab0dac00c44cff2552"
REQUIRES="appdata-tools dconf gsettings-desktop-schemas vte yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr             \
            --disable-static          \
            --disable-migration       \
            --disable-search-provider
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

