#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-system-monitor/3.12/gnome-system-monitor-3.12.2.tar.xz"
MD5SUMLIST="dc9f4ffa25ebee2795821251ef0d73db"
REQUIRES="gnome-icon-theme gtkmm3 libgtop librsvg yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-wnck
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

