#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="baobab brasero cheese eog epiphany evince file-roller gedit gnome-calculator gnome-nettool gnome-screenshot gnome-system-monitor gnome-terminal gucharmap nautilus network-manager-applet seahorse totem"
TAGS="group"

