#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnumeric/1.12/gnumeric-1.12.17.tar.xz"
MD5SUMLIST="7d488148ca5192178f60d2d33c32c9e7"
REQUIRES="goffice010 rarian"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e "s@zz-application/zz-winassoc-xls;@@" -i gnumeric.desktop.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

