#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.5.1.tar.bz2"
MD5SUMLIST="8fb46b336200807a12a12a5760b4a39d"
REQUIRES="libassuan"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --disable-fd-passing \
            --disable-gpgsm-test
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

