#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/project/gptfdisk/gptfdisk/0.8.10/gptfdisk-0.8.10.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/gptfdisk-0.8.10-convenience-1.patch"
MD5SUMLIST="9cf4246c181c324bdbd553fe9b348373
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../gptfdisk-0.8.10-convenience-1.patch
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

