#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.grantlee.org/grantlee-0.4.0.tar.gz"
MD5SUMLIST="fa8a2e9be7be7e3a89e700679e6f3014"
REQUIRES="cmake qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$QT4DIR \
      -DCMAKE_BUILD_TYPE=Release  \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

