#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz"
MD5SUMLIST="5b6a829b2ac94efcd5fa3c223ed6d3ae"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

ln -v -s ${FAKEROOT}/usr/share/graphviz/doc \
         ${FAKEROOT}/usr/share/doc/graphviz-2.38.0

#################
} # END OF FILE #
#################

