#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/silgraphite/graphite2-1.2.4.tgz"
MD5SUMLIST="2ef839348fe28e3b923bf8cced440227"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

