#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gst-plugins-good/0.10/gst-plugins-good-0.10.31.tar.xz"
MD5SUMLIST="555845ceab722e517040bab57f9ace95"
REQUIRES="gst-plugins-base"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e "/input:/d" sys/v4l2/gstv4l2bufferpool.c
sed -i -e "/case V4L2_CID_HCENTER/d" -e "/case V4L2_CID_VCENTER/d" sys/v4l2/v4l2_calls.c
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-gtk=3.0
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C docs/plugins install-data

#################
} # END OF FILE #
#################

