#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gst-plugins-base/0.10/gst-plugins-base-0.10.36.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/gst-plugins-base-0.10.36-gcc_4_9_0_i686-1.patch"
MD5SUMLIST="3d2337841b132fe996e5eb2396ac9438
            dontverify"
REQUIRES="gstreamer pango"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../gst-plugins-base-0.10.36-gcc_4_9_0_i686-1.patch

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

