#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.4.0.tar.xz"
MD5SUMLIST="1ff06280b03b9098a706d1290d8bb3bd"
REQUIRES="gstreamer10"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-package-name="GStreamer Base Plugins 1.4.0 BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/svn/"
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

