#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gstreamer/0.10/gstreamer-0.10.36.tar.xz"
MD5SUMLIST="15389c73e091b1dda915279c388b9cb2"
REQUIRES="glib2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i  -e '/YYLEX_PARAM/d'                                       \
        -e '/parse-param.*scanner/i %lex-param { void *scanner }' \
            gst/parse/grammar.y

./configure --prefix=/usr \
            --disable-static
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gstreamer-0.10/design
install -v -m644 docs/design/*.txt \
                    ${FAKEROOT}/usr/share/doc/gstreamer-0.10/design

if [ -d ${FAKEROOT}/usr/share/doc/gstreamer-0.10/faq/html ]; then
    chown -v -R root:root \
        ${FAKEROOT}/usr/share/doc/gstreamer-0.10/*/html
fi

gst-launch -v fakesrc num_buffers=5 ! fakesink

#################
} # END OF FILE #
#################

