#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gucharmap/3.12/gucharmap-3.12.1.tar.xz"
MD5SUMLIST="3a39588c963e7848a4850a0b5975211b"
REQUIRES="desktop-file-utils gtk+3 yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-vala
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

