#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/hdparm/hdparm-9.43.tar.gz"
MD5SUMLIST="f73233be118d86c779a8463d8b6a3cdb"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} binprefix=/usr install

#################
} # END OF FILE #
#################

