#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.icu-project.org/files/icu4c/53.1/icu4c-53_1-src.tgz"
MD5SUMLIST="b73baa6fbdfef197608d1f69300919b9"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd source
CXX=g++ ./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

