#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/inkscape/inkscape-0.48.5.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/inkscape-0.48.5-gc-1.patch"
MD5SUMLIST="431cda5cd40cd4fdf2b89db1bdcce61f
            dontverify"
REQUIRES="boost gc gsl gtkmm2 libxslt"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../inkscape-0.48.5-gc-1.patch

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

