#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/joe-editor/joe-3.7.tar.gz"
MD5SUMLIST="66de1b073e869ba12abbfcde3885c577"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --sysconfdir=/etc --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

