#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.mozilla.org/pub/mozilla.org/js/mozjs-24.2.0.tar.bz2"
MD5SUMLIST="5db79c10e049a2dc117a6e6a3bc78a8e"
REQUIRES="libffi nspr python2 zip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd js/src
./configure --prefix=/usr       \
            --enable-readline   \
            --enable-threadsafe \
            --with-system-ffi   \
            --with-system-nspr
make

make DESTDIR=${FAKEROOT} install
find ${FAKEROOT}/usr/include/mozjs-24/         \
     ${FAKEROOT}/usr/lib/libmozjs-24.a         \
     ${FAKEROOT}/usr/lib/pkgconfig/mozjs-24.pc \
     -type f -exec chmod -v 644 {} \;

#################
} # END OF FILE #
#################

