#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12.tar.gz"
MD5SUMLIST="3ca4bbb881dfc4017e8021b5e0a8c491"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i s/-Werror// Makefile.in
./configure --prefix=/usr --disable-static
make -j1

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

