#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://launchpad.net/debian/+archive/primary/+files/junit4_4.11.orig.tar.gz"
MD5SUMLIST="b4d163832583dcec8bedb5427c795cc4"
REQUIRES="apache-ant unzip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../hamcrest-1.3.tgz
cp -v hamcrest-1.3/hamcrest-core-1.3{,-sources}.jar lib/
ant dist

install -v -m755 -d ${FAKEROOT}/usr/share/{doc,java}/junit-4.11
chown -R root:root .

cp -v -R junit*/javadoc/*             ${FAKEROOT}/usr/share/doc/junit-4.11
cp -v junit*/junit*.jar               ${FAKEROOT}/usr/share/java/junit-4.11
cp -v hamcrest-1.3/hamcrest-core*.jar ${FAKEROOT}/usr/share/java/junit-4.11

export CLASSPATH=$CLASSPATH:/usr/share/java/junit-4.11

#################
} # END OF FILE #
#################

