#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/k3b/k3b-2.0.2.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/k3b-2.0.2-ffmpeg2-1.patch"
MD5SUMLIST="c86113af31a2032e57fd2f302b5f637a
            dontverify"
REQUIRES="kde-runtime libkcddb libsamplerate"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../k3b-2.0.2-ffmpeg2-1.patch

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX \
      -DSYSCONF_INSTALL_DIR=/etc/kde     \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

