#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/4.13.3/src/kde-runtime-4.13.3.tar.xz"
MD5SUMLIST="8b7b7e217744779f33dd8aa38015efa0"
REQUIRES="kdelibs"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX         \
      -DSYSCONF_INSTALL_DIR=/etc                  \
      -DCMAKE_BUILD_TYPE=Release                  \
      -DSAMBA_INCLUDE_DIR=/usr/include/samba-4.0 \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install
ln -sfv ../lib/kde4/libexec/kdesu $KDE_PREFIX/bin/kdesu

#################
} # END OF FILE #
#################

