#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="akonadi attica automoc4 baloo baloo-widgets kactivities kde-base-artwork kde-baseapps kde-runtime kde-workspace kdelibs kdepimlibs kfilemetadata oxygen-icons phonon phonon-backend-gstreamer phonon-backend-vlc polkit-kde-agent polkit-qt qimageblitz"
TAGS="group"

