#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/4.13.3/src/kde-workspace-4.11.11.tar.xz"
MD5SUMLIST="cbd3311713b42d4856c66281fbe7a212"
REQUIRES="kactivities qimageblitz xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX           \
      -DSYSCONF_INSTALL_DIR=/etc                   \
      -DCMAKE_BUILD_TYPE=Release                   \
      -DINSTALL_PYTHON_FILES_IN_PYTHON_PREFIX=TRUE \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install
mkdir -p ${FAKEROOT}/usr/share/xsessions
ln -sf $KDE_PREFIX/share/apps/kdm/sessions/kde-plasma.desktop \
       ${FAKEROOT}/usr/share/xsessions/kde-plasma.desktop

cat >> ${FAKEROOT}/etc/pam.d/kde << "EOF"
# Begin /etc/pam.d/kde

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     include        system-auth

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/kde
EOF
cat > ${FAKEROOT}/etc/pam.d/kde-np << "EOF"
# Begin /etc/pam.d/kde-np

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     required       pam_permit.so

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/kde-np
EOF
cat > ${FAKEROOT}/etc/pam.d/kscreensaver << "EOF"
# Begin /etc/pam.d/kscreensaver

auth    include system-auth
account include system-account

# End /etc/pam.d/kscreensaver
EOF

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 37 kdm
useradd -c "KDM Daemon Owner" -d /var/lib/kdm -g kdm \
        -u 37 -s /bin/false kdm
install -o kdm -g kdm -dm755 /var/lib/kdm

#################
} # END OF FILE #
#################

