#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.nlnetlabs.nl/downloads/ldns/ldns-1.6.17.tar.gz"
MD5SUMLIST="a79423bcc4129e6d59b616b1cae11e5e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --with-drill
make

make doc

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/ldns-1.6.17
install -v -m644 doc/html/* ${FAKEROOT}/usr/share/doc/ldns-1.6.17

#################
} # END OF FILE #
#################

