#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.videolan.org/pub/libdvdcss/1.3.0/libdvdcss-1.3.0.tar.bz2"
MD5SUMLIST="7f0fdb3ff91d638f5e45ed7536f7eb67"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/libdvdcss-1.3.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

