#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://dvdnav.mplayerhq.hu/releases/libdvdread-4.9.9.tar.xz"
MD5SUMLIST="1aa8ad88e462791a8e77d628a63ee788"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/libdvdread-4.9.9
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

