#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgsf/1.14/libgsf-1.14.30.tar.xz"
MD5SUMLIST="e7b672ef37ef6a853ce149c03e4d3a63"
REQUIRES="glib2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

