#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.musicbrainz.org/pub/musicbrainz/historical/libmusicbrainz-2.1.5.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/libmusicbrainz-2.1.5-missing-includes-1.patch"
MD5SUMLIST="d5e19bb77edd6ea798ce206bd05ccc5f
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libmusicbrainz-2.1.5-missing-includes-1.patch
./configure --prefix=/usr
make

(cd python && python setup.py build)

make DESTDIR=${FAKEROOT} install
install -v -m644 -D docs/mb_howto.txt \
    ${FAKEROOT}/usr/share/doc/libmusicbrainz-2.1.5/mb_howto.txt

(cd python && python setup.py install)

#################
} # END OF FILE #
#################

