#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libmng/libmng-2.0.2.tar.xz"
MD5SUMLIST="3804bf2523af9b4e0670b5982b3bf984"
REQUIRES="lcms2 libjpeg-turbo"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "s:#include <jpeg:#include <stdio.h>\n&:" libmng_types.h

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d        ${FAKEROOT}/usr/share/doc/libmng-2.0.2
install -v -m644 doc/*.txt ${FAKEROOT}/usr/share/doc/libmng-2.0.2

#################
} # END OF FILE #
#################

