#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://github.com/downloads/metabrainz/libmusicbrainz/libmusicbrainz-5.0.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/libmusicbrainz-5.0.1-build_system-1.patch"
MD5SUMLIST="a0406b94c341c2b52ec0fe98f57cadf3
            dontverify"
REQUIRES="cmake neon"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libmusicbrainz-5.0.1-build_system-1.patch

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

