#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://nice.freedesktop.org/releases/libnice-0.1.7.tar.gz"
MD5SUMLIST="ed74abea19b3f049baf095f137388f2a"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --without-gstreamer-0.10
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

