#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.25.tar.gz"
MD5SUMLIST="e2b7bb637e01022c7d20f95f9c3990a2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} htmldocdir=/usr/share/doc/libsndfile-1.0.25 install

#################
} # END OF FILE #
#################

