#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.mega-nerd.com/SRC/libsamplerate-0.1.8.tar.gz"
MD5SUMLIST="1c7fb25191b4e6e3628d198a66a84f47"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} htmldocdir=/usr/share/doc/libsamplerate-0.1.8 install

#################
} # END OF FILE #
#################

