#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://dl.lm-sensors.org/lm-sensors/releases/lm_sensors-3.3.5.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/lm_sensors-3.3.5-upstream_fixes-1.patch"
MD5SUMLIST="da506dedceb41822e64865f6ba34828a
            dontverify"
REQUIRES="which"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../lm_sensors-3.3.5-upstream_fixes-1.patch
make PREFIX=/usr        \
     BUILD_STATIC_LIB=0 \
     MANDIR=/usr/share/man

make DESTDIR=${FAKEROOT} PREFIX=/usr        \
     BUILD_STATIC_LIB=0 \
     MANDIR=/usr/share/man install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/lm_sensors-3.3.5
cp -rv              README INSTALL doc/* \
                    ${FAKEROOT}/usr/share/doc/lm_sensors-3.3.5

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sensors-detect

#################
} # END OF FILE #
#################

