#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/lxsession-0.4.9.2.tar.gz"
MD5SUMLIST="bc3eb71936dbdf813e9ac2f00ab948f0"
REQUIRES="dbus-glib gtk+2 libgee lsb-release polkit vala"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

