#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.midnight-commander.org/mc-4.8.12.tar.xz"
MD5SUMLIST="7ecccc03df060cd0ca1414a5a14e6649"
REQUIRES="glib2 pcre"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --enable-charset
make

make DESTDIR=${FAKEROOT} install
cp -v doc/keybind-migration.txt ${FAKEROOT}/usr/share/mc

#################
} # END OF FILE #
#################

