#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-3.3.2.tar.xz"
MD5SUMLIST="44698d351501cac6a89072dc877eb220"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/Wall -Werror/Wall/' Makefile

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

