#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://pkgs.fedoraproject.org/repo/pkgs/mod_dnssd/mod_dnssd-0.6.tar.gz/bed3d95a98168bf0515922d1c05020c5/mod_dnssd-0.6.tar.gz"
MD5SUMLIST="bed3d95a98168bf0515922d1c05020c5"
REQUIRES="apache avahi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/unixd_setup_child/ap_&/' src/mod_dnssd.c

./configure --prefix=/usr \
            --disable-lynx
make

make DESTDIR=${FAKEROOT} install
sed -i 's| usr| ${FAKEROOT}/usr|' ${FAKEROOT}/etc/httpd/httpd.conf

#################
} # END OF FILE #
#################

