#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/mpg123/mpg123-1.20.1.tar.bz2"
MD5SUMLIST="1b3e8765aa608e306ede1ec507b67b23"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-module-suffix=.so
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

