#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.1.1.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/MPlayer-1.1.1-giflib_fixes-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/MPlayer-1.1.1-live_fixes-1.patch
          http://www.mplayerhq.hu/MPlayer/skins/Clearlooks-1.5.tar.bz2"
MD5SUMLIST="39dd55f30eb5403f219a606e79a6648a
            dontverify
            dontverify
            dontverify"
REQUIRES="yasm"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################


patch -Np1 -i ../MPlayer-1.1.1-giflib_fixes-1.patch
patch -Np1 -i ../MPlayer-1.1.1-live_fixes-1.patch
sed -i 's:libsmbclient.h:samba-4.0/&:'      configure stream/stream_smb.c
sed -i 's/EGifCloseFile(new_gif/&, NULL/'   libvo/vo_gif89a.c
sed -i 's/DGifCloseFile(priv->gif/&, NULL/' libmpdemux/demux_gif.c

./configure --prefix=/usr            \
            --confdir=/etc/mplayer   \
            --enable-dynamic-plugins \
            --enable-menu            \
            --enable-gui
make

make doc

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/mplayer-1.1.1
install -v -m644    DOCS/HTML/en/* \
                    ${FAKEROOT}/usr/share/doc/mplayer-1.1.1

install -v -m644 etc/codecs.conf ${FAKEROOT}/etc/mplayer

install -v -m644 etc/*.conf ${FAKEROOT}/etc/mplayer

tar -xvf ../Clearlooks-1.5.tar.bz2 \
       -C ${FAKEROOT}/usr/share/mplayer/skins
ln -sfv Clearlooks ${FAKEROOT}/usr/share/mplayer/skins/default

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

