#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/nautilus/3.12/nautilus-3.12.2.tar.xz"
MD5SUMLIST="cc802f9b49504b8ca5f5ec11fd4418c6"
REQUIRES="gnome-desktop libnotify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --disable-tracker    \
            --disable-packagekit
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

