#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.ncftp.com/ncftp/ncftp-3.2.5-src.tar.bz2"
MD5SUMLIST="b05c7a6d5269c04891f02f43d4312b30"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make -C libncftp shared
make

make DESTDIR=${FAKEROOT} -C libncftp soinstall
make DESTDIR=${FAKEROOT} install

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

