#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://nmap.org/dist/nmap-6.46.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/nmap-6.46-fix_tests-1.patch"
MD5SUMLIST="5a36ad3a63d5b7ea5514f745a397436a
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../nmap-6.46-fix_tests-1.patch

./configure --prefix=/usr
make -j1

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

