#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/opal/3.10/opal-3.10.10.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/opal-3.10.10-ffmpeg2-1.patch"
MD5SUMLIST="6efa1b4c5e0ad6460019b4c6df0898d7
            dontverify"
REQUIRES="ptlib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../opal-3.10.10-ffmpeg2-1.patch

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
chmod -v 644 ${FAKEROOT}/usr/lib/libopal_s.a

#################
} # END OF FILE #
#################

