#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/p7zip/p7zip_9.20.1_src_all.tar.bz2"
MD5SUMLIST="bd6caaea567dc0d995c990c5cc883c89"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e 's/chmod 555/chmod 755/' -e 's/chmod 444/chmod 644/' install.sh
make all3

make DESTDIR=${FAKEROOT} DEST_HOME=/usr \
     DEST_MAN=/usr/share/man \
     DEST_SHARE_DOC=/usr/share/doc/p7zip-9.20.1 install

#################
} # END OF FILE #
#################

