#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/paps/paps-0.6.8.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/paps-0.6.8-freetype_fix-1.patch"
MD5SUMLIST="e9508132bf27609bf2fded2bfd9cb3f1
            dontverify"
REQUIRES="pango"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../paps-0.6.8-freetype_fix-1.patch
./configure --prefix=/usr --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d                 ${FAKEROOT}/usr/share/doc/paps-0.6.8
install -v -m644 doxygen-doc/html/* ${FAKEROOT}/usr/share/doc/paps-0.6.8

#################
} # END OF FILE #
#################

