#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://archive.xfce.org/src/apps/parole/0.5/parole-0.5.4.tar.bz2"
MD5SUMLIST="fa25b069c90bb9d59fef46e77c98f9b0"
REQUIRES="gst-plugins-base gst10-plugins-base libxfce4ui"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

