#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pidgin/pidgin-2.10.9.tar.bz2"
MD5SUMLIST="10a4a69d077893f6dd3438cd8af94e81"
REQUIRES="gtk+2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr       \
            --sysconfdir=/etc   \
            --disable-avahi     \
            --disable-gtkspell  \
            --disable-gstreamer \
            --disable-meanwhile \
            --disable-idn       \
            --disable-nm        \
            --disable-vv        \
            --disable-tcl
make

make DESTDIR=${FAKEROOT} install
mkdir -pv ${FAKEROOT}/usr/share/doc/pidgin-2.10.9
cp -v README doc/gtkrc-2.0 ${FAKEROOT}/usr/share/doc/pidgin-2.10.9

mkdir -pv ${FAKEROOT}/usr/share/doc/pidgin-2.10.9/api
cp -v doc/html/* ${FAKEROOT}/usr/share/doc/pidgin-2.10.9/api

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

