#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://pm-utils.freedesktop.org/releases/pm-utils-1.4.1.tar.gz"
MD5SUMLIST="1742a556089c36c3a89eb1b957da5a60"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/pm-utils-1.4.1
make

make DESTDIR=${FAKEROOT} install

install -v -m644 man/*.1 ${FAKEROOT}/usr/share/man/man1
install -v -m644 man/*.8 ${FAKEROOT}/usr/share/man/man8
ln -sv pm-action.8 ${FAKEROOT}/usr/share/man/man8/pm-suspend.8
ln -sv pm-action.8 ${FAKEROOT}/usr/share/man/man8/pm-hibernate.8
ln -sv pm-action.8 ${FAKEROOT}/usr/share/man/man8/pm-suspend-hybrid.8

#################
} # END OF FILE #
#################

