#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/pth/pth-2.0.7.tar.gz"
MD5SUMLIST="9cb4a25331a4c4db866a31cbe507c793"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's#$(LOBJS): Makefile#$(LOBJS): pth_p.h Makefile#' Makefile.in
./configure --prefix=/usr           \
            --disable-static        \
            --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/pth-2.0.7
install -v -m644    README PORTING SUPPORT TESTS \
                    ${FAKEROOT}/usr/share/doc/pth-2.0.7

#################
} # END OF FILE #
#################

