#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://freedesktop.org/software/pulseaudio/releases/pulseaudio-5.0.tar.xz"
MD5SUMLIST="c43749838612f4860465e83ed62ca38e"
REQUIRES="json-c libsndfile"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

find . -name "Makefile.in" | xargs sed -i "s|(libdir)/@PACKAGE@|(libdir)/pulse|"
./configure --prefix=/usr         \
            --sysconfdir=/etc     \
            --localstatedir=/var  \
            --disable-bluez4      \
            --disable-rpath       \
            --with-module-dir=/usr/lib/pulse/modules
make

make DESTDIR=${FAKEROOT} install

rm ${FAKEROOT}/etc/dbus-1/system.d/pulseaudio-system.conf

#################
} # END OF FILE #
#################

