#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2"
MD5SUMLIST="20337132c4ab06c1146ad384d55372c5"
REQUIRES="cairo python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./waf configure --prefix=/usr
./waf build

./waf install

#################
} # END OF FILE #
#################

