#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://cairographics.org/releases/pycairo-1.10.0.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_python_3_4-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_unpack-1.patch"
MD5SUMLIST="e6fd3f2f1e6a72e0db0868c4985669c5
            dontverify
            dontverify"
REQUIRES="cairo python3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../pycairo-1.10.0-waf_unpack-1.patch
wafdir=$(./waf unpack)
pushd $wafdir
patch -Np1 -i ../pycairo-1.10.0-waf_python_3_4-1.patch
popd
unset wafdir
PYTHON=/usr/bin/python3 ./waf configure --prefix=/usr
./waf build

./waf install

#################
} # END OF FILE #
#################

