#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/pygobject/2.28/pygobject-2.28.6.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/pygobject-2.28.6-fixes-1.patch"
MD5SUMLIST="9415cb7f2b3a847f2310ccea258b101e
            dontverify"
REQUIRES="glib2 py2cairo"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../pygobject-2.28.6-fixes-1.patch
./configure --prefix=/usr --disable-introspection
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

