#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://people.freedesktop.org/~takluyver/pyxdg-0.25.tar.gz"
MD5SUMLIST="bedcdb3a0ed85986d40044c87f23477c"
REQUIRES="python2 python3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

python setup.py install --optimize=1

python3 setup.py install --optimize=1

#################
} # END OF FILE #
#################

