#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://delta.affinix.com/download/qca/2.0/qca-2.0.3.tar.bz2"
MD5SUMLIST="fc15bd4da22b8096c51fcfe52d2fa309"
REQUIRES="qt4 which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '217s@set@this->set@' src/botantools/botan/botan/secmem.h
./configure --prefix=$QT4DIR \
            --certstore-path=/etc/ssl/ca-bundle.crt \
	    --no-separate-debug-info
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

