#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/qimageblitz/qimageblitz-0.0.6.tar.bz2"
MD5SUMLIST="0ae2f7d4e0876764a97ca73799f61df4"
REQUIRES="cmake qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

