#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/qjson/qjson-0.8.1.tar.bz2"
MD5SUMLIST="323fbac54a5a20c0b8fe45c1ced03e2d"
REQUIRES="cmake qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$QT4DIR \
      -DCMAKE_BUILD_TYPE=Release \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

