#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/qpdf/qpdf-5.1.2.tar.gz"
MD5SUMLIST="0bd15ef5eea5f628951ab456c84e78ec"
REQUIRES="pcre"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/qpdf-5.1.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

