#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.qt-project.org/official_releases/qt/5.3/5.3.1/single/qt-everywhere-opensource-src-5.3.1.tar.xz"
MD5SUMLIST="f9a24a0d5645efa0715b6ff0fa13d60f"
REQUIRES="alsa-lib mesalib postlfs xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

export QT5LINK=/usr

./configure -prefix         /usr               \
            -sysconfdir     /etc/xdg           \
            -bindir         /usr/bin           \
            -headerdir      /usr/include/qt5   \
            -archdatadir    /usr/lib/qt5       \
            -datadir        /usr/share/qt5     \
            -docdir         /usr/share/doc/qt5 \
            -translationdir /usr/share/qt5/translations \
            -examplesdir    /usr/share/doc/qt5/examples \
            -confirm-license   \
            -opensource        \
            -dbus-linked       \
            -openssl-linked    \
            -system-sqlite     \
            -no-nis            \
            -nomake examples   \
            -optimized-qmake
make

find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;

make DESTDIR=${FAKEROOT} install

sed -e "s:$PWD/qtbase:/usr/lib/qt5:g" \
    -i ${FAKEROOT}/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri

find ${FAKEROOT}/usr/lib/lib{qgsttools_p,Qt5*}.prl -exec sed -i -r \
     '/^QMAKE_PRL_BUILD_DIR/d;s/(QMAKE_PRL_LIBS =).*/\1/' {} \;

export QT5DIR=/opt/qt-5.3.1
export QT5LINK=/opt/qt5

./configure -prefix     $QT5DIR  \
            -sysconfdir /etc/xdg \
            -confirm-license     \
            -opensource          \
            -dbus-linked         \
            -openssl-linked      \
            -system-sqlite       \
            -no-nis              \
            -nomake examples     \
            -optimized-qmake
make

make DESTDIR=${FAKEROOT} install
ln -svfn $QT5DIR ${FAKEROOT}/opt/qt5

find $QT5DIR -name qt_lib_bootstrap_private.pri \
   -exec sed -i -e "s:$PWD/qtbase:/$QT5DIR/lib/:g" {} \;

find $QT5DIR -name \*.prl \
   -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

install -v -dm755 ${FAKEROOT}/usr/share/pixmaps/

install -v -Dm644 qttools/src/assistant/assistant/images/assistant-128.png \
                  ${FAKEROOT}/usr/share/pixmaps/assistant-qt5.png

install -v -Dm644 qttools/src/designer/src/designer/images/designer.png \
                  ${FAKEROOT}/usr/share/pixmaps/designer-qt5.png

install -v -Dm644 qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  ${FAKEROOT}/usr/share/pixmaps/linguist-qt5.png

install -v -Dm644 qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  ${FAKEROOT}/usr/share/pixmaps/qdbusviewer-qt5.png

install -dm755 ${FAKEROOT}/usr/share/applications

cat > ${FAKEROOT}/usr/share/applications/assistant-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Assistant 
Comment=Shows Qt5 documentation and examples
Exec=$QT5LINK/bin/assistant
Icon=assistant-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF

cat > ${FAKEROOT}/usr/share/applications/designer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=$QT5LINK/bin/designer
Icon=designer-qt5.png
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > ${FAKEROOT}/usr/share/applications/linguist-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=$QT5LINK/bin/linguist
Icon=linguist-qt5.png
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > ${FAKEROOT}/usr/share/applications/qdbusviewer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 QDbusViewer 
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=$QT5LINK/bin/qdbusviewer
Icon=qdbusviewer-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF

cat > ${FAKEROOT}/etc/profile.d/qt5.sh << EOF
# Begin ${FAKEROOT}/etc/profile.d/qt5.sh

QT5DIR=/usr
export QT5DIR

# End ${FAKEROOT}/etc/profile.d/qt5.sh
EOF

# (*) Utilize the ld.so.conf directory
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

cat >> ${FAKEROOT}/etc/ld.so.conf.d/qt5.conf << EOF
# Begin Qt addition

/opt/qt5/lib

# End Qt addition
EOF

ldconfig

cat > ${FAKEROOT}/etc/profile.d/qt5.sh << EOF
# Begin ${FAKEROOT}/etc/profile.d/qt5.sh

QT5DIR=/opt/qt5

pathappend /opt/qt5/bin           PATH
pathappend /opt/qt5/lib/pkgconfig PKG_CONFIG_PATH

export QT5DIR

# End ${FAKEROOT}/etc/profile.d/qt5.sh
EOF

cat > ${FAKEROOT}/usr/bin/setqt4 << 'EOF'
if [ "x$QT5DIR" != "x/usr" ]; then pathremove  $QT5DIR/bin; fi
if [ "x$QT4DIR" != "x/usr" ]; then pathprepend $QT4DIR/bin; fi
echo $PATH
EOF

cat > ${FAKEROOT}/usr/bin/setqt5 << 'EOF'
if [ "x$QT4DIR" != "x/usr" ]; then pathremove  $QT4DIR/bin; fi
if [ "x$QT5DIR" != "x/usr" ]; then pathprepend $QT5DIR/bin; fi
echo $PATH
EOF

#################
} # END OF FILE #
#################

