#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/rpcbind/rpcbind-0.2.1.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140810.tar.bz2"
MD5SUMLIST="0a5f9c2142af814c55d957aaab3bcc68
            179a6c22d0f7d2619cba4eb794fdc1cb"
REQUIRES="libtirpc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "/servname/s:rpcbind:sunrpc:" src/rpcbind.c
sed -i "/error = getaddrinfo/s:rpcbind:sunrpc:" src/rpcinfo.c

./configure --prefix=/usr --bindir=/sbin --with-rpcuser=root
make

make DESTDIR=${FAKEROOT} install

includeBootscript rpcbind

#################
} # END OF FILE #
#################

