#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.bz2"
MD5SUMLIST="ed9b8565bdeccb401d628ec8d54a0774"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr   \
            --enable-shared \
            --docdir=/usr/share/doc/ruby-2.1.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

