#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.tuxfamily.org/sawfish/sawfish-1.10.tar.xz"
MD5SUMLIST="562814495cc991f29eb4b8e2d8dea05a"
REQUIRES="rep-gtk which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-pango
make

make DESTDIR=${FAKEROOT} install

cat >> ${FAKEROOT}/etc/alternatives/xinitrc/sawfish.xinitrc << "EOF"
exec sawfish
EOF

#################
} # END OF FILE #
#################

