#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.kernel.org/pub/linux/bluetooth/sbc-1.2.tar.xz"
MD5SUMLIST="ec65c444ad4c32aa85702641045b19e9"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static --disable-tester
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

