#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.libsdl.org/release/SDL-1.2.15.tar.gz"
MD5SUMLIST="9d96df8417572a2afb781a7c4c811a85"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/_XData32/s:register long:register _Xconst long:' src/video/x11/SDL_x11sym.h

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/SDL-1.2.15/html
install -v -m644    docs/html/*.html \
                    ${FAKEROOT}/usr/share/doc/SDL-1.2.15/html

#################
} # END OF FILE #
#################

