#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/seahorse/3.12/seahorse-3.12.2.tar.xz"
MD5SUMLIST="998578f6dbde86037107c137161662f2"
REQUIRES="gcr gnupg2 gpgme libsecret yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --bindir=/usr/bin \
            --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

