#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://simpleburn.tuxfamily.org/IMG/bz2/simpleburn-1.6.5.tar.bz2"
MD5SUMLIST="de658ab5af00e7bcb1e948d5c45da7b9"
REQUIRES="cmake gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DBURNING=LIBBURNIA ..
make

make DESTDIR=${FAKEROOT} install

usermod -a -G cdrom <username>

#################
} # END OF FILE #
#################

