#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.surina.net/soundtouch/soundtouch-1.8.0.tar.gz"
MD5SUMLIST="d02c6c91cb13901ca273a2b4b143ce41"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed "s@AM_CONFIG_HEADER@AC_CONFIG_HEADERS@g" -i configure.ac
./bootstrap

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} pkgdocdir=/usr/share/doc/soundtouch-1.8.0 install 

#################
} # END OF FILE #
#################

