#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/startup-notification/releases/startup-notification-0.12.tar.gz"
MD5SUMLIST="2cd77326d4dcaed9a5a23a1232fb38e9"
REQUIRES="x7lib xcb-util"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D doc/startup-notification.txt \
    ${FAKEROOT}/usr/share/doc/startup-notification-0.12/startup-notification.txt

#################
} # END OF FILE #
#################

