#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.sudo.ws/sudo/dist/sudo-1.8.10p3.tar.gz"
MD5SUMLIST="fcd8d0d9f9f0397d076ee901e242ed39"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr              \
            --libexecdir=/usr/lib      \
            --with-all-insults         \
            --with-env-editor          \
            --docdir=/usr/share/doc/sudo-1.8.10p3 \
            --with-passprompt="[sudo] password for %p"
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
chmod 644 ${FAKEROOT}/etc/pam.d/sudo

#################
} # END OF FILE #
#################

