#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/time/time-1.7.tar.gz"
MD5SUMLIST="e38d2b8b34b1ca259cf7b053caac32b3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/$(ACLOCAL)//' Makefile.in
sed -i 's/lu", ptok ((UL) resp->ru.ru_maxrss)/ld", resp->ru.ru_maxrss/' time.c
./configure --prefix=/usr --infodir=/usr/share/info
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

