#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/totem/3.12/totem-3.12.2.tar.xz"
MD5SUMLIST="939272a90d60c075b957a220c87bd680"
REQUIRES="clutter-gst2 clutter-gtk gnome-icon-theme gst10-plugins-bad gst10-plugins-good libpeas totem-pl-parser yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

