#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/traceroute/traceroute-2.0.20.tar.gz"
MD5SUMLIST="559f104e155e0e14ee0c717776a745fa"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} prefix=/usr install
mv ${FAKEROOT}/usr/bin/traceroute ${FAKEROOT}/bin
ln -sv -f traceroute ${FAKEROOT}/bin/traceroute6
ln -sv -f traceroute.8 ${FAKEROOT}/usr/share/man/man8/traceroute6.8

#################
} # END OF FILE #
#################

