#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.unixodbc.org/unixODBC-2.3.2.tar.gz"
MD5SUMLIST="5e4528851eda5d3d4aed249b669bd05b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc/unixODBC
make

make DESTDIR=${FAKEROOT} install

find doc -name "Makefile*" -delete
chmod 644 doc/{lst,ProgrammerManual/Tutorial}/*

install -v -m755 -d ${FAKEROOT}/usr/share/doc/unixODBC-2.3.2
cp      -v -R doc/* ${FAKEROOT}/usr/share/doc/unixODBC-2.3.2

#################
} # END OF FILE #
#################

