#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://valgrind.org/downloads/valgrind-3.9.0.tar.bz2"
MD5SUMLIST="0947de8112f946b9ce64764af7be6df2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's|2.18|2.19|'      configure
sed -i 's|/doc/valgrind||' docs/Makefile.in

./configure --prefix=/usr \
            --datadir=/usr/share/doc/valgrind-3.9.0
make

pushd docs
make download-docs
popd

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

