#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/vorbis/vorbis-tools-1.4.0.tar.gz"
MD5SUMLIST="567e0fb8d321b2cd7124f8208b8b90e6"
REQUIRES="libvorbis"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-vcut \
            --without-curl
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

