#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://webkitgtk.org/releases/webkitgtk-2.4.4.tar.xz"
MD5SUMLIST="79edd28d32172abc17a8861622cc274f"
REQUIRES="gst10-plugins-base gtk+3 icu libsecret libsoup libwebp mesalib ruby sqlite udev-extras which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/generate-gtkdoc --rebase/s:^:# :' GNUmakefile.in

./configure --prefix=/usr          \
            --enable-introspection
make

make DESTDIR=${FAKEROOT} install
rm -rf ${FAKEROOT}/usr/share/gtk-doc/html/webkitgtk-2.0
mv -vi ${FAKEROOT}/usr/share/gtk-doc/html/webkitgtk{,-2.0}

#################
} # END OF FILE #
#################

