#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.debian.org/debian/pool/main/w/whois/whois_5.1.5.tar.xz"
MD5SUMLIST="2723e8916cb301999466fd0017d00def"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} prefix=/usr install-whois
make DESTDIR=${FAKEROOT} prefix=/usr install-mkpasswd
make DESTDIR=${FAKEROOT} prefix=/usr install-pos

#################
} # END OF FILE #
#################

