#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/wireless_tools.29.tar.gz"
MD5SUMLIST="e06c222e186f7cc013fd272d023710cb"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make PREFIX=${FAKEROOT}/usr INSTALL_MAN=/usr/share/man install

#################
} # END OF FILE #
#################

