#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="agg at-spi2-atk at-spi2-core atk atkmm cairo cairomm clutter clutter-gst2 clutter-gtk cogl fltk freeglut gdk-pixbuf glu goffice010 gtk+2 gtk+3 gtk-engines gtkmm2 gtkmm3 imlib2 libdrm libepoxy libglade libnotify libxklavier pango pangomm qt4 qt5 startup-notification webkitgtk webkitgtk2 xulrunner"
TAGS="group"

