#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://oligarchy.co.uk/xapian/1.2.17/xapian-core-1.2.17.tar.xz"
MD5SUMLIST="493117bf45e5471e86b4fc5d6d8069dc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
          --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

