#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://people.freedesktop.org/~rdieter/xdg-utils/xdg-utils-1.1.0-rc2.tar.gz"
MD5SUMLIST="38b6f1d38cb02297ddbf64dba0a907a4"
REQUIRES="fop links lynx w3m x7app xmlto"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

