#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://oss.sgi.com/projects/xfs/cmd_tars/xfsprogs-3.2.1.tar.gz"
MD5SUMLIST="5c6905932029c8f9207fe5a0a8aac24b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DEBUG=-DNDEBUG INSTALL_USER=root INSTALL_GROUP=root \
     LOCAL_CONFIGURE_OPTIONS="--enable-readline"

make DESTDIR=${FAKEROOT} install install-dev
rm -rfv ${FAKEROOT}/lib/libhandle.{a,la,so}
ln -sfv ../../lib/libhandle.so.1 ${FAKEROOT}/usr/lib/libhandle.so
sed -i "s@libdir='/lib@libdir='/usr/lib@g" ${FAKEROOT}/usr/lib/libhandle.la

#################
} # END OF FILE #
#################

