#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/xine/xine-lib-1.2.6.tar.xz"
MD5SUMLIST="02ee3c2380273989b4b016903209e05e"
REQUIRES="alsa ffmpeg pulseaudio xorg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --disable-vcd     \
            --docdir=/usr/share/doc/xine-lib-1.2.6
make

doxygen doc/Doxyfile

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/xine-lib-1.2.6/api
install -v -m644    doc/api/* \
                    ${FAKEROOT}/usr/share/doc/xine-lib-1.2.6/api

#################
} # END OF FILE #
#################

