#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.xsane.org/download/xsane-0.999.tar.gz"
MD5SUMLIST="9927f21e1ab6ba96315e7f0e30746deb"
REQUIRES="gtk+2 sane"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e 's/png_ptr->jmpbuf/png_jmpbuf(png_ptr)/' src/xsane-save.c
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} xsanedocdir=/usr/share/doc/xsane-0.999 install
ln -v -s ../../doc/xsane-0.999 ${FAKEROOT}/usr/share/sane/xsane/doc

ln -v -s <browser> ${FAKEROOT}/usr/bin/netscape

ln -v -s ${FAKEROOT}/usr/bin/xsane ${FAKEROOT}/usr/lib/gimp/2.0/plug-ins/

#################
} # END OF FILE #
#################

