#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xvid.org/downloads/xvidcore-1.3.3.tar.gz"
MD5SUMLIST="8ecddfe488cb3a82d792fc7efbf51d62"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd build/generic
sed -i 's/^LN_S=@LN_S@/& -f -v/' platform.inc.in
./configure --prefix=/usr
make

sed -i '/libdir.*STATIC_LIB/ s/^/#/' Makefile
make DESTDIR=${FAKEROOT} install

chmod -v 755 ${FAKEROOT}/usr/lib/libxvidcore.so.4.3

install -v -m755 -d ${FAKEROOT}/usr/share/doc/xvidcore-1.3.3/examples
install -v -m644 ../../doc/* ${FAKEROOT}/usr/share/doc/xvidcore-1.3.3
install -v -m644 ../../examples/* \
    ${FAKEROOT}/usr/share/doc/xvidcore-1.3.3/examples

#################
} # END OF FILE #
#################

