#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.zsh.org/pub/zsh-5.0.5.tar.bz2
          http://www.zsh.org/pub/zsh-5.0.5-doc.tar.bz2"
MD5SUMLIST="6156dc2f19b0a067bdbc0fb7f81e2017
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar --strip-components=1 -xvf ../zsh-5.0.5-doc.tar.bz2

sed -e '/attr.mdh/ d' -e '/attr.pro/ d'                                        \
    -e '/include <sys\/xattr.h>/ a\\n#include "attr.mdh"\n#include "attr.pro"' \
    -i Src/Modules/attr.c

./configure --prefix=/usr         \
            --bindir=/bin         \
            --sysconfdir=/etc/zsh \
            --enable-etcdir=/etc/zsh
make

makeinfo  Doc/zsh.texi --html      -o Doc/html
makeinfo  Doc/zsh.texi --html --no-split --no-headers \
                                   -o Doc/zsh.html
makeinfo  Doc/zsh.texi --plaintext -o Doc/zsh.txt

texi2pdf  Doc/zsh.texi -o Doc/zsh.pdf

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} infodir=/usr/share/info install.info

install -v -m755 -d ${FAKEROOT}/usr/share/doc/zsh-5.0.5/html
install -v -m644    Doc/html/* \
                    ${FAKEROOT}/usr/share/doc/zsh-5.0.5/html
install -v -m644    Doc/zsh.{html,txt} \
                    ${FAKEROOT}/usr/share/doc/zsh-5.0.5

make DESTDIR=${FAKEROOT} htmldir=/usr/share/doc/zsh-5.0.5/html install.html
install -v -m644 Doc/zsh.dvi ${FAKEROOT}/usr/share/doc/zsh-5.0.5

install -v -m644 Doc/zsh.pdf \
        ${FAKEROOT}/usr/share/doc/zsh-5.0.5

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/zsh
/bin/zsh-5.0.5
EOF

#################
} # END OF FILE #
#################

