#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.8/caja-1.8.1.tar.xz"
MD5SUMLIST="e81bbec307c8aafd9663f4927f309ba4"
REQUIRES="libunique mate-desktop shared-mime-info"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.8 \
        --localstatedir=/var \
        --libexecdir=/usr/lib/caja \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/caja
install -v -m644 docs/*.{txt,dia,pdf,sxw,faq,html} \
        ${FAKEROOT}/usr/share/doc/caja

#################
} # END OF FILE #
#################

