#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

REQUIRES="compiz-fusion firefox flash-plugin fsos-nox mate nm-applet slim"
TAGS="group"

