#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.8/libmatekbd-1.8.0.tar.xz"
MD5SUMLIST="e2d7c8ee6d5375ed923c2399eb63aeab"
REQUIRES="gtk+2 libxklavier mate-common"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.8
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

