#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.8/mate-notification-daemon-1.8.0.tar.xz"
MD5SUMLIST="f9cb50a86c30bccc8728adcbf6a04f32"
REQUIRES="dbus-glib libcanberra libnotify libwnck2 mate-common"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --libexecdir=/usr/lib/mate-notification-daemon \
        --localstatedir=/var \
        --sysconfdir=/etc/mate/1.8 \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

