#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.8/mate-settings-daemon-1.8.1.tar.xz"
MD5SUMLIST="ba264ff243f70136de486923f502710e"
REQUIRES="dbus-glib libmatekbd mate-desktop"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.8 \
        --libexecdir=/usr/lib/mate-settings-daemon \
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

