#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://www.memtest.org/download/4.20/memtest86+-4.20.tar.gz"
MD5SUMLIST="ef62c2f5be616676c8c62066dedc46b3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

cp -v memtest.bin ${FAKEROOT}/boot/memtest86

#################
} # END OF FILE #
#################

