#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://www.kernel.org/pub/linux/utils/boot/syslinux/4.xx/syslinux-4.07.tar.bz2"
MD5SUMLIST="9ff6e1b94efab931fb4717b600d88779"
REQUIRES="nasm python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make spotless

make

make INSTALLROOT=${FAKEROOT} install

#################
} # END OF FILE #
#################

