#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

WGETLIST="http://ftp.gnome.org/pub/GNOME/core/3.13/3.13.4/sources/yelp-tools-3.13.3.tar.xz"
MD5SUMLIST="c4be924aca75c31b60e5ad10a7154fff"
REQUIRES="yelp-xsl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

