#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.xz"
MD5SUMLIST="7fc29854c520f56b07aa232a0f880292"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.14.1

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

