#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans


WGETLIST="https://ftp.gnu.org/gnu/bash/bash-4.4-beta.tar.gz"
          
MD5SUMLIST="b58cc55f7270d8784ec099545eb37e72"
            

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                    \
            --bindir=/bin                    \
            --docdir=/usr/share/doc/bash-4.3 \
            --without-bash-malloc            \
            --with-installed-readline

make

make DESTDIR=${FAKEROOT} install

# (*) This will add the '/bin/sh' symlink to the package archive.
ln -s bash ${FAKEROOT}/bin/sh

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools --without-bash-malloc

make

make install

ln -sv bash /tools/bin/sh

#################
} # END OF FILE #
#################

