#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://alpha.gnu.org/gnu/bc/bc-1.06.95.tar.bz2
          http://www.linuxfromscratch.org/patches/lfs/development/bc-1.06.95-memory_leak-1.patch"
MD5SUMLIST="5126a721b73f97d715bb72c13c889035
            877e81fba316fe487ec23501059d54b8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../bc-1.06.95-memory_leak-1.patch

./configure --prefix=/usr           \
            --with-readline         \
            --mandir=/usr/share/man \
            --infodir=/usr/share/info

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

