#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-20140815.tar.bz2"
MD5SUMLIST="f64dde51156e04cd125725bb3e3b66ce"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DESTDIR=${FAKEROOT} install

# Last update: 2014-06-07 (LFS SVN-20140604)

# ********************************************
# ********************************************
# *** System Configuration and Bootscripts ***
# ********************************************
# ********************************************

# =====================================
# === General Network Configuration ===
# =====================================

# --- Creating Network Interface Configuration Files ---
# (*) Skipped, we assume you will install DHCP from BLFS

# --- Configuring the system hostname ---
# (*) Set in rc.site

# --- Customizing the ${FAKEROOT}/etc/hosts File ---
# (*) Only create an entry for localhost

cat > ${FAKEROOT}/etc/hosts << "EOF"
# Begin /etc/hosts

127.0.0.1 localhost

# End /etc/hosts
EOF

## Creating the '/etc/resolv.conf' File
#cat > ${FAKEROOT}/etc/resolv.conf << "EOF"
## Begin /etc/resolv.conf
#
## -- Note --
##  The Google Public IPv4 DNS servers used here should be usable on any machine
##  connected to the internet. However, you may want to replace them with the
##  adresses provided to you by your ISP.
#
#nameserver 8.8.8.8
#nameserver 8.8.4.4
#
## End ${FAKEROOT}/etc/resolv.conf
#EOF


# ===================================================
# === System V Bootscript Usage and Configuration ===
# ===================================================

# --- Configuring Sysvinit ---

cat > ${FAKEROOT}/etc/inittab << "EOF"
# Begin /etc/inittab

id:3:initdefault:

si::sysinit:/etc/rc.d/init.d/rc S

l0:0:wait:/etc/rc.d/init.d/rc 0
l1:S1:wait:/etc/rc.d/init.d/rc 1
l2:2:wait:/etc/rc.d/init.d/rc 2
l3:3:wait:/etc/rc.d/init.d/rc 3
l4:4:wait:/etc/rc.d/init.d/rc 4
l5:5:wait:/etc/rc.d/init.d/rc 5
l6:6:wait:/etc/rc.d/init.d/rc 6

ca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -r now

su:S016:once:/sbin/sulogin

1:2345:respawn:/sbin/agetty --noclear tty1 9600
2:2345:respawn:/sbin/agetty tty2 9600
3:2345:respawn:/sbin/agetty tty3 9600
4:2345:respawn:/sbin/agetty tty4 9600
5:2345:respawn:/sbin/agetty tty5 9600
6:2345:respawn:/sbin/agetty tty6 9600

# End /etc/inittab
EOF

# --- Configuring the System Clock ---
# (*) Set in rc.site

# --- Configuring the Linux Console ---
# (*) Set in rc.site

# --- The rc.site File ---
# (*) The uncommented lines in this file have been modified from the original

cat > ${FAKEROOT}/etc/sysconfig/rc.site << "EOF"
# rc.site
# Optional parameters for boot scripts.

# Distro Information
# These values, if specified here, override the defaults
#DISTRO="Linux From Scratch" # The distro name
#DISTRO_CONTACT="lfs-dev@linuxfromscratch.org" # Bug report address
#DISTRO_MINI="LFS" # Short name used in filenames for distro config

# Define custom colors used in messages printed to the screen

# Please consult `man console_codes` for more information
# under the "ECMA-48 Set Graphics Rendition" section
#
# Warning: when switching from a 8bit to a 9bit font,
# the linux console will reinterpret the bold (1;) to
# the top 256 glyphs of the 9bit font.  This does
# not affect framebuffer consoles

# These values, if specified here, override the defaults
#BRACKET="\\033[1;34m" # Blue
#FAILURE="\\033[1;31m" # Red
#INFO="\\033[1;36m"    # Cyan
#NORMAL="\\033[0;39m"  # Grey
#SUCCESS="\\033[1;32m" # Green
#WARNING="\\033[1;33m" # Yellow

# Use a colored prefix
# These values, if specified here, override the defaults
#BMPREFIX="     "
#SUCCESS_PREFIX="${SUCCESS}  *  ${NORMAL}"
#FAILURE_PREFIX="${FAILURE}*****${NORMAL}"
#WARNING_PREFIX="${WARNING} *** ${NORMAL}"

# Interactive startup
#IPROMPT="yes" # Whether to display the interactive boot prompt
#itime="3"    # The amount of time (in seconds) to display the prompt

# The total length of the distro welcome string, without escape codes
#wlen=$(echo "Welcome to ${DISTRO}" | wc -c )
#welcome_message="Welcome to ${INFO}${DISTRO}${NORMAL}"

# The total length of the interactive string, without escape codes
#ilen=$(echo "Press 'I' to enter interactive startup" | wc -c )
#i_message="Press '${FAILURE}I${NORMAL}' to enter interactive startup"

# Set scripts to skip the file system check on reboot
#FASTBOOT=yes

# Skip reading from the console
#HEADLESS=yes

# Write out fsck progress if yes
#VERBOSE_FSCK=no

# Speed up boot without waiting for settle in udev
#OMIT_UDEV_SETTLE=y

# Speed up boot without waiting for settle in udev_retry
#OMIT_UDEV_RETRY_SETTLE=yes

# Skip cleaning /tmp if yes
#SKIPTMPCLEAN=no

# For setclock
UTC=1
#CLOCKPARAMS=

# For consolelog
LOGLEVEL=1

# For network
HOSTNAME=localhost

# Delay between TERM and KILL signals at shutdown
#KILLDELAY=3

# Optional sysklogd parameters
#SYSKLOGD_PARMS="-m 0"

# Console parameters
UNICODE=1
KEYMAP="us-acentos"
KEYMAP_CORRECTIONS="euro2"
FONT="lat0-16 -m 8859-15"
#LEGACY_CHARSET=
EOF


# ====================================
# === The Bash Shell Startup Files ===
# ====================================

# (*) Following BLFS, we place the language configuration into
#     '/etc/profile.d/i18n.sh'.
mkdir -pv ${FAKEROOT}/etc/profile.d

# (*) Set locale to US English (UTF-8)
cat > ${FAKEROOT}/etc/profile.d/i18n.sh << EOF
# Set up i18n variables
export LANG="en_US.UTF-8"
EOF

# (*) Minimal '/etc/profile' in case the 'postlfs' script from BLFS will not be
#     installed.
cat > ${FAKEROOT}/etc/profile << "EOF"
# Minimal profile, which loads configuration from /etc/profile.d
for script in /etc/profile.d/*.sh ; do
  if [ -r ${script} ] ; then
    . ${script}
  fi
done
EOF


# ========================================
# === Creating the '/etc/inputrc' File ===
# ========================================

cat > ${FAKEROOT}/etc/inputrc << "EOF"
# Begin /etc/inputrc
# Modified by Chris Lynn <roryo@roryo.dynup.net>

# Allow the command prompt to wrap to the next line
set horizontal-scroll-mode Off

# Enable 8bit input
set meta-flag On
set input-meta On

# Turns off 8th bit stripping
set convert-meta Off

# Keep the 8th bit for display
set output-meta On

# none, visible or audible
set bell-style none

# All of the following map the escape sequence of the value
# contained in the 1st argument to the readline specific functions
"\eOd": backward-word
"\eOc": forward-word

# for linux console
"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[5~": beginning-of-history
"\e[6~": end-of-history
"\e[3~": delete-char
"\e[2~": quoted-insert

# for xterm
"\eOH": beginning-of-line
"\eOF": end-of-line

# for Konsole
"\e[H": beginning-of-line
"\e[F": end-of-line

# End /etc/inputrc
EOF


# **************************************
# **************************************
# *** Making the LFS System Bootable ***
# **************************************
# **************************************

# ======================================
# === Creating the '/etc/fstab' File ===
# ======================================

# (*) This file can be used as is, if your system is installed to a single
#     partition. Otherwise, it must be modified to reflect your set up.

cat > ${FAKEROOT}/etc/fstab << "EOF"
# Begin /etc/fstab

# file system  mount-point  type     options             dump  fsck
#                                                              order

rootfs         /            auto     defaults            0     0

#/dev/<xxx>    /            <fff>    defaults            1     1
#/dev/<yyy>    swap         swap     pri=1               0     0

proc           /proc        proc     nosuid,noexec,nodev 0     0
sysfs          /sys         sysfs    nosuid,noexec,nodev 0     0
devpts         /dev/pts     devpts   gid=5,mode=620      0     0
tmpfs          /run         tmpfs    defaults            0     0
devtmpfs       /dev         devtmpfs mode=0755,nosuid    0     0

# End /etc/fstab
EOF

#################
} # END OF FILE #
#################

