#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz"
MD5SUMLIST="72c832680cf0999caedbe5b265c8c1bd"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-libgdbm-compat

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

