#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/gperf/gperf-3.0.4.tar.gz"
MD5SUMLIST="c1f1db32fb6598d6a93e6e88796a8632"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.0.4

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

