#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://anduin.linuxfromscratch.org/sources/LFS/lfs-packages/conglomeration/iana-etc/iana-etc-2.30.tar.bz2"
MD5SUMLIST="3ba3afb1d1b261383d247f46cb135ee8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

