#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.2.tar.gz"
MD5SUMLIST="aa1a9a132259db83e66c1f3265065ba2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

echo '#define PATH_PROCNET_DEV "/proc/net/dev"' >> ifconfig/system/linux.h 

./configure --prefix=/usr  \
            --localstatedir=/var   \
            --disable-logger       \
            --disable-whois        \
            --disable-servers

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/{hostname,ping,ping6,traceroute} ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/ifconfig ${FAKEROOT}/sbin

#################
} # END OF FILE #
#################

