#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://www.greenwoodsoftware.com/less/less-458.tar.gz"
MD5SUMLIST="935b38aa2e73c888c210dedf8fd94f49"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

