#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.3.0.tar.gz"
MD5SUMLIST="242428c01dca255cdcb2195073a9c6ed"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

