#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="https://ftp.gnu.org/gnu/make/make-4.1.tar.bz2"
MD5SUMLIST="57a7a224a822f94789a587ccbcedff69"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools --without-guile

make

make install

#################
} # END OF FILE #
#################

