#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-3.71.tar.xz"
MD5SUMLIST="9a2a288f1e481045c991e0cb476127d8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

