#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://www.multiprecision.org/mpc/download/mpc-1.0.2.tar.gz"
MD5SUMLIST="68fadff3358fb3e7976c7a398a0af4c3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/mpc-1.0.2

make
make html

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-html

#################
} # END OF FILE #
#################

