#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://downloads.sourceforge.net/project/psmisc/psmisc/psmisc-22.21.tar.gz"
MD5SUMLIST="935c0fd6eb208288262b385fa656f1bf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/fuser   ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/killall ${FAKEROOT}/bin

#################
} # END OF FILE #
#################

