#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://pkg-shadow.alioth.debian.org/releases/shadow-4.2.1.tar.xz"
MD5SUMLIST="2bfafe7d4962682d31b5eba65dba4fc8"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;

sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

sed -i 's/1000/999/' etc/useradd

./configure --sysconfdir=/etc --with-group-name-max-length=32

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/passwd ${FAKEROOT}/bin

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pwconv

grpconv

sed -i 's/yes/no/' /etc/default/useradd

# (*) The password for root will be set during interactive configuration.
#passwd root

#################
} # END OF FILE #
#################

