#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/tar/tar-1.28.tar.xz"
MD5SUMLIST="49b6306167724fe48f419a33a5beb857"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
            --bindir=/bin

make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} -C doc install-html docdir=/usr/share/doc/tar-1.28

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

