#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/texinfo/texinfo-5.2.tar.xz"
MD5SUMLIST="cb489df8a7ee9d10a236197aefdb32c5"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} TEXMF=/usr/share/texmf install-tex

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pushd /usr/share/info
# (*) Without '-f', 'rm' would fail if 'dir' does not exist
rm -fv dir
for f in *
  do install-info $f dir 2>/dev/null
done
popd

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

