#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2"
MD5SUMLIST="607e135c559be642f210094ad023dc65"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

ln -sv vim ${FAKEROOT}/usr/bin/vi
for L in  ${FAKEROOT}/usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done

ln -sv ../vim/vim74/doc ${FAKEROOT}/usr/share/doc/vim-7.4

cat > ${FAKEROOT}/etc/vimrc << "EOF"
" Begin /etc/vimrc

set nocompatible
set backspace=2
syntax on
if (&term == "iterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
EOF

#################
} # END OF FILE #
#################

