#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.42_01.tar.gz"
MD5SUMLIST="a4650aebcc464bb91113c2c356da8210"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

perl Makefile.PL

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

