#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://alsa.cybermirror.org/lib/alsa-lib-1.0.28.tar.bz2"
MD5SUMLIST="c9e21b88a2b3e6e12ea7ba0f3b271fc3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

make DESTDIR=${FAKEROOT} install

# (*) Suppress the building of documentation which requires additional software to be installed
#make doc

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -d -m755 ${FAKEROOT}/usr/share/doc/alsa-lib-1.0.28/html
#install -v -m644 doc/doxygen/html/* ${FAKEROOT}/usr/share/doc/alsa-lib-1.0.28/html

#################
} # END OF FILE #
#################

