#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/dconf/0.20/dconf-0.20.0.tar.xz"
MD5SUMLIST="542db78e4867ac575ec0f69f79b3eebd"
REQUIRES="dbus docbook-xsl glib2 libxml2 libxslt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-editor
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

