#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.22.tar.xz"
MD5SUMLIST="c6b9f9aac1ea143091178c23437e6cd0"
REQUIRES="glib2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

update-desktop-database /usr/share/applications

#################
} # END OF FILE #
#################

