#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://fedorahosted.org/releases/e/l/elfutils/0.159/elfutils-0.159.tar.bz2"
MD5SUMLIST="1f45a18231c782ccd0966059e2e42ea9"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --program-prefix="eu-"
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

