#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ffmpeg.org/releases/ffmpeg-2.3.3.tar.bz2"
MD5SUMLIST="72361d3b8717b6db3ad2b9da8df7af5e"
REQUIRES="fdk-aac lame libass libtheora libvorbis libvpx x264 x7lib yasm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/-lflite"/-lflite -lasound"/' configure
./configure --prefix=/usr        \
            --enable-gpl         \
            --enable-version3    \
            --enable-nonfree     \
            --disable-static     \
            --enable-shared      \
            --disable-debug      \
            --enable-libass      \
            --enable-libfdk-aac  \
            --enable-libmp3lame  \
            --enable-libtheora   \
            --enable-libvorbis   \
            --enable-libvpx      \
            --enable-libx264     \
            --enable-x11grab
make
gcc tools/qt-faststart.c -o tools/qt-faststart

# (*) Suppress the building of documentation which requires additional software to be installed
#sed -i '$s/$/\n\n@bye/' doc/{git-howto,nut,fate}.texi
#sed -i '/machine:i386/ s/\\/@backslashchar{}/g' doc/platform.texi
#
#pushd doc
#for DOCNAME in `basename -s .html *.html`
#do
#    texi2pdf -b $DOCNAME.texi
#    texi2dvi -b $DOCNAME.texi
#    dvips -o    $DOCNAME.ps   \
#                $DOCNAME.dvi
#done
#popd
#unset DOCNAME

# (*) Don't run test suites
#make fate-rsync SAMPLES=fate-suite/

# (*) Don't run test suites
#make fate SAMPLES=fate-suite/ | tee ../fate.log
#grep ^TEST ../fate.log | wc -l

make DESTDIR=${FAKEROOT} install
install -v -m755    tools/qt-faststart ${FAKEROOT}/usr/bin
install -v -m755 -d ${FAKEROOT}/usr/share/doc/ffmpeg
install -v -m644    doc/*.txt \
                    ${FAKEROOT}/usr/share/doc/ffmpeg

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -m644 doc/*.html \
#                 ${FAKEROOT}/usr/share/doc/ffmpeg

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -m755 -d ${FAKEROOT}/usr/share/doc/ffmpeg/api
#cp -vr doc/doxy/html/* ${FAKEROOT}/usr/share/doc/ffmpeg/api
#find ${FAKEROOT}/usr/share/doc/ffmpeg/api -type f -exec chmod -c 0644 "{}" ";"
#find ${FAKEROOT}/usr/share/doc/ffmpeg/api -type d -exec chmod -c 0755 "{}" ";"

#################
} # END OF FILE #
#################

