#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://fribidi.org/download/fribidi-0.19.6.tar.bz2"
MD5SUMLIST="ce93d862344991173dabb609bf93ca1d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "s|glib/gstrfuncs\.h|glib.h|" charset/fribidi-char-sets.c
sed -i "s|glib/gmem\.h|glib.h|"      lib/mem.h
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

