#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.gnutls.org/gcrypt/gnutls/v3.3/gnutls-3.3.6.tar.xz"
MD5SUMLIST="84264c7d3f5fad14b7990a4e71aa340e"
REQUIRES="nettle"
RECOMMENDS="libtasn1"

# (*) Install 'libtasn1' because it will otherwise install it's own outdated version

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-default-trust-store-file=/etc/ssl/ca-bundle.crt
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C doc/reference install-data-local

#################
} # END OF FILE #
#################

