#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk+/3.12/gtk+-3.12.2.tar.xz"
MD5SUMLIST="0d6d8f9f79132b3b47475d047b369b1c"
REQUIRES="at-spi2-atk gdk-pixbuf pango"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --enable-broadway-backend \
            --enable-x11-backend      \
            --disable-wayland-backend
make

make DESTDIR=${FAKEROOT} install

# (*) Example configuration
#mkdir -p ${FAKEROOT}/etc/skel/.config/gtk-3.0
#cat > ${FAKEROOT}/etc/skel/.config/gtk-3.0/settings.ini << "EOF"
#[Settings]
#gtk-theme-name = Adwaita
#gtk-fallback-icon-theme = gnome
#EOF

cat > ${FAKEROOT}/etc/gtk-3.0/settings.ini << "EOF"
[Settings]
gtk-theme-name = Clearwaita
gtk-fallback-icon-theme = elementary
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

glib-compile-schemas /usr/share/glib-2.0/schemas

gtk-query-immodules-3.0 --update-cache

glib-compile-schemas /usr/share/glib-2.0/schemas

#################
} # END OF FILE #
#################

