#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk-doc/1.20/gtk-doc-1.20.tar.xz"
MD5SUMLIST="58532fed036f72fc3bfd4fe79473247b"
REQUIRES="docbook docbook-xsl itstool libxslt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

