#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://dri.freedesktop.org/libdrm/libdrm-2.4.56.tar.bz2"
MD5SUMLIST="93fdb76d392ce27b23561afb8f70db81"
RECOMMENDS="x7lib"

# (*) Install 'x7lib' because it enables Intel KMS API support required by Mesa (and Mesa requires x7lib anyway)

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e "/pthread-stubs/d" -i configure.ac
autoreconf -fiv
./configure --prefix=/usr --enable-udev
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

