#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/libevdev/libevdev-1.2.2.tar.xz"
MD5SUMLIST="7c1ee9c2069489b2a25dfde6f8e2ff6a"
REQUIRES="python2 xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cat >> test/valgrind.suppressions << "EOF"
{
   <timer_create@@GLIBC_2.3.3-2>
   Memcheck:Param
   timer_create(evp)
   fun:timer_create@@GLIBC_2.3.3
   fun:check_get_clockid
   fun:srunner_run
   fun:main
}
EOF

./configure $XORG_CONFIG
make

# (*) Don't run test suites.
#make check

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

