#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz"
MD5SUMLIST="5c3a34309d8b98640827e5d0991a4015"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/libogg-1.3.2 --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

