#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libsigc++/2.3/libsigc++-2.3.2.tar.xz"
MD5SUMLIST="e75fbd6f5cc34d058a9dabec96245dc8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/type_traits.h/i\#include <sigc++/visit_each.h>' \
 sigc++/macros/limit_reference.h.m4
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

