#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.osgeo.org/libtiff/tiff-4.0.3.tar.gz"
MD5SUMLIST="051c1068e6a0627f461948c365290410"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/glDrawPixels/a glFlush();' tools/tiffgt.c
./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

