#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.xz"
MD5SUMLIST="9eeabf1ad65b7f41533854a59f7a716d"
REQUIRES="libogg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/png_\(sizeof\)/\1/g' examples/png2theora.c
./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

cd examples/.libs
for E in *; do
  install -v -m755 $E ${FAKEROOT}/usr/bin/theora_${E}
done

#################
} # END OF FILE #
#################

