#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libunique/1.1/libunique-1.1.6.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/libunique-1.1.6-upstream_fixes-1.patch"
MD5SUMLIST="7955769ef31f1bc4f83446dbb3625e6d
            4ce1bf51879a679b55be831f31bf3a2f"
REQUIRES="gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libunique-1.1.6-upstream_fixes-1.patch
autoreconf -fi

./configure --prefix=/usr  \
            --disable-dbus \
            --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

