#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/vaapi/releases/libva/libva-1.3.1.tar.bz2"
MD5SUMLIST="eb4db967f068854444b597071c66b480"
REQUIRES="mesalib xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -p m4
autoreconf   -f
./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

