#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://github.com/i-rinat/libvdpau-va-gl/archive/v0.3.4.tar.gz"
MD5SUMLIST="09ceb2f75eafccc9b002d35ede0de6a5"
REQUIRES="cmake ffmpeg glib2 glu libva libvdpau xorg-env"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$XORG_PREFIX ..
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "export VDPAU_DRIVER=va_gl" >> /etc/profile.d/xorg.sh

#################
} # END OF FILE #
#################

