#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libwnck/2.30/libwnck-2.30.7.tar.xz"
MD5SUMLIST="3d20f26105a2fd878899d6ecdbe9a082"
REQUIRES="gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-static \
            --program-suffix=-1
make GETTEXT_PACKAGE=libwnck-1

make DESTDIR=${FAKEROOT} GETTEXT_PACKAGE=libwnck-1 install

#################
} # END OF FILE #
#################

