#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xcb.freedesktop.org/dist/libxcb-1.11.tar.bz2"
MD5SUMLIST="5a873ebd383d1a60612dd6ec6b42c781"
REQUIRES="libXau xcb-proto xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed "s/pthread-stubs//" -i configure
./configure $XORG_CONFIG    \
            --enable-xinput \
            --docdir='${datadir}'/doc/libxcb-1.11
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

