#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/lsb/files/lsb_release/1.4/lsb-release-1.4.tar.gz"
MD5SUMLIST="30537ef5a01e0ca94b7b8eb6a36bb1e4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "s|n/a|unavailable|" lsb_release

./help2man -N --include ./lsb_release.examples \
              --alt_version_key=program_version ./lsb_release > lsb_release.1

install -v -m 644 lsb_release.1 ${FAKEROOT}/usr/share/man/man1/lsb_release.1
install -v -m 755 lsb_release ${FAKEROOT}/usr/bin/lsb_release

#################
} # END OF FILE #
#################

