#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.oberhumer.com/opensource/lzo/download/lzo-2.08.tar.gz"
MD5SUMLIST="fcec64c26a0f4f4901468f360029678f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                    \
            --enable-shared                  \
            --disable-static                 \
            --docdir=/usr/share/doc/lzo-2.08
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

