#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/nettle/nettle-2.7.1.tar.gz"
MD5SUMLIST="003d5147911317931dd453520eb234a5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

sed -i '/^install-here/ s/install-static//' Makefile

make DESTDIR=${FAKEROOT} install
chmod -v 755 ${FAKEROOT}/usr/lib/libhogweed.so.2.5 ${FAKEROOT}/usr/lib/libnettle.so.4.7
install -v -m755 -d ${FAKEROOT}/usr/share/doc/nettle-2.7.1
install -v -m644 nettle.html ${FAKEROOT}/usr/share/doc/nettle-2.7.1

#################
} # END OF FILE #
#################

