#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://fedorahosted.org/releases/n/e/newt/newt-0.52.17.tar.gz"
MD5SUMLIST="f36d4d908965a0c89fd6fd8b61a6118b"
REQUIRES="popt slang"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e 's/^LIBNEWT =/#&/' \
    -e '/install -m 644 $(LIBNEWT)/ s/^/#/' \
    -e 's/$(LIBNEWT)/$(LIBNEWTSONAME)/g' \
    -i Makefile.in
./configure --prefix=/usr --with-gpm-support
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

