#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/pango/1.36/pango-1.36.6.tar.xz"
MD5SUMLIST="1c27523c3f3a4efe4d9d303d0d240320"
REQUIRES="cairo harfbuzz x7lib"
RECOMMENDS="gobject-introspection"
POSTINST="true"

# (*) Install 'gobject-introspection' because it avoids compilation order problems when building Gnome

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pango-querymodules --update-cache

# (*) Configuration information
#Pango/ModulesPath

#################
} # END OF FILE #
#################

