#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pcre/pcre-8.35.tar.bz2"
MD5SUMLIST="6aacb23986adccd9b3bc626c00979958"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                     \
            --docdir=/usr/share/doc/pcre-8.35 \
            --enable-unicode-properties       \
            --enable-pcre16                   \
            --enable-pcre32                   \
            --enable-pcregrep-libz            \
            --enable-pcregrep-libbz2          \
            --enable-pcretest-libreadline     \
            --disable-static
make

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/lib/libpcre.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libpcre.so) ${FAKEROOT}/usr/lib/libpcre.so

#################
} # END OF FILE #
#################

