#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://archive.xfce.org/src/xfce/thunar/1.6/Thunar-1.6.3.tar.bz2"
MD5SUMLIST="4f10d5d5576ce5127308d6badbac3afa"
REQUIRES="exo libxfce4ui"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/Thunar-1.6.3
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

