#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/linuxwacom/xf86-input-wacom-0.25.0.tar.bz2"
MD5SUMLIST="2cf57400fbd9e35eb16b50ad9fe32de1"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --with-systemd-unit-dir=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

