#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/archive/individual/driver/xf86-input-vmmouse-13.0.0.tar.bz2"
MD5SUMLIST="34f9f64ee6a1a51fc8266a9af24e1e07"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG \
            --with-udev-rules-dir=/lib/udev/rules.d \
            --without-hal-callouts-dir \
            --without-hal-fdi-dir
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

