#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="libevdev libva libvdpau libvdpau-va-gl x7driver-ati x7driver-cirrus x7driver-evdev x7driver-fbdev x7driver-intel x7driver-mach64 x7driver-mga x7driver-nouveau x7driver-openchrome x7driver-r128 x7driver-savage x7driver-sis x7driver-synaptics x7driver-tdfx x7driver-vesa x7driver-vmmouse x7driver-vmware x7driver-wacom"
TAGS="group"

