#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/font/font-util-1.3.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/encodings-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-adobe-100dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-adobe-75dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-adobe-utopia-100dpi-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-adobe-utopia-75dpi-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-adobe-utopia-type1-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-alias-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-arabic-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-100dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-75dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-lucidatypewriter-100dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-lucidatypewriter-75dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-ttf-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bh-type1-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bitstream-100dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bitstream-75dpi-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-bitstream-type1-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-cronyx-cyrillic-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-cursor-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-daewoo-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-dec-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-ibm-type1-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-isas-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-jis-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-micro-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-misc-cyrillic-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-misc-ethiopic-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-misc-meltho-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-misc-misc-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-mutt-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-schumacher-misc-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-screen-cyrillic-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-sony-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-sun-misc-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-winitzki-cyrillic-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/font/font-xfree86-type1-1.0.4.tar.bz2"
MD5SUMLIST="ddfc8a89d597651408369d940d03d06b
            0f2d6546d514c5cc4ecf78a60657a5c1
            1347c3031b74c9e91dc4dfa53b12f143
            6c9f26c92393c0756f3e8d614713495b
            66fb6de561648a6dce2755621d6aea17
            e99276db3e7cef6dccc8a57bc68aeba7
            fcf24554c348df3c689b91596d7f9971
            6d25f64796fef34b53b439c2e9efa562
            cc0726e4a277d6ed93b8e09c1f195470
            9f11ade089d689b9d59e0f47d26f39cd
            565494fc3b6ac08010201d79c677a7a7
            c8b73a53dcefe3e8d3907d3500e484a9
            f6d65758ac9eb576ae49ab24c5e9019a
            e8ca58ea0d3726b94fe9f2c17344be60
            53ed9a42388b7ebb689bdfc374f96a22
            6b223a54b15ecbd5a1bc52312ad790d8
            d7c0588c26fac055c0dd683fdd65ac34
            5e0c9895d69d2632e2170114f8283c11
            e452b94b59b9cfd49110bb49b6267fba
            3e0069d4f178a399cffe56daa95c2b63
            0571bf77f8fab465a5454569d9989506
            6e7c5108f1b16d7a1c7b2c9760edd6e5
            bfb2593d2102585f45daa960f43cb3c4
            a2401caccbdcf5698e001784dbd43f1a
            cb7b57d7800fd9e28ec35d85761ed278
            143c228286fe9c920ab60e47c1b60b67
            96109d0890ad2b6b0e948525ebb0aba8
            6306c808f7d7e7d660dfb3859f9091d2
            e3e7b0fda650adc7eb6964ff3c486b1c
            c88eb44b3b903d79fb44b860a213e623
            56b0296e8862fc1df5cdbb4efe604e86
            e805feb7c4f20e6bfb1118d19d972219
            6f3fdcf2454bf08128a651914b7948ca
            beef61a9b0762aba8af7b736bb961f86
            948f2e07810b4f31195185921470f68d
            829a3159389b7f96f629e5388bfee67b
            3eeb3fb44690b477d510bbd8f86cf5aa"
REQUIRES="xcursor-themes xorg-env"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

install -v -d -m755 ${FAKEROOT}/usr/share/fonts
ln -svfn $XORG_PREFIX/share/fonts/X11/OTF ${FAKEROOT}/usr/share/fonts/X11-OTF
ln -svfn $XORG_PREFIX/share/fonts/X11/TTF ${FAKEROOT}/usr/share/fonts/X11-TTF

#################
} # END OF FILE #
#################

