#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.3.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libX11-1.6.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libFS-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXt-1.1.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXpm-3.5.11.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXaw-1.0.12.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXfixes-5.0.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXcomposite-0.4.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.8.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXcursor-1.1.14.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXdamage-1.1.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXfont-1.5.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXft-2.3.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXi-1.7.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.4.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXres-1.0.7.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXtst-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXv-1.0.10.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.8.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-1.1.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libpciaccess-0.13.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.0.8.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libxshmfence-1.1.tar.bz2"
MD5SUMLIST="a615e17d9fee6f097fc3b716eacb3dca
            c35d6ad95b06635a524579e88622fdb5
            52df7c4c1f0badd9f82ab124fb32eb97
            a8a0dbd2299b2568d8c919883f5c8501
            addfb1e897ca8079531669c7c7711726
            499a7773c65aba513609fe651853c5f3
            7a773b16165e39e938650bcc9027c1d5
            03149823ae57bb02d0cec90d5b97d56c
            41d92ab627dfa06568076043f3e089e4
            769ee12a43611cdebd38094eaf83f3f0
            7446f5fba888672aad068b29c0928ba3
            b985b85f8b9386c85ddcfe1073906b4d
            f7a218dcbf6f0848599c6c36fc65c51a
            2bd9a15fcf64d216e63b8d129e4f1f1c
            1e7c17afbbce83e2215917047c57d1b3
            0cf292de2a9fa2e9a939aefde68fd34f
            ad2919764933e075bb0361ad5caa3d19
            664629bfa7cdf8b984155019fd395dcb
            331b3a2a3a1a78b5b44cfbd43f86fcfe
            9c4a69c34b19ec1e4212e849549544cb
            9336dc46ae3bf5f81c247f7131461efd
            210ed9499a3d9c96e3a221629b7d39b0
            45ef29206a6b58254c81bea28ec6c95f
            25c6b366ac3dc7a12c5d79816ce96a59
            e0af49d7d758b990e6fef629722d4aca
            2e4014e9d55c430e307999a6b3dd256d
            d7dd9b9df336b7dd4028b6b56542ff2c
            e46f6ee4f4567349a3189044fe1bb712
            ba983eba5a9f05d152a0725b8e863151
            b7c0d3afce14eedca57312a3141ec13a
            19e6533ae64abba0773816a23f2b9507
            2dd10448c1166e71a176206a8dfabe6d"
REQUIRES="fontconfig libxcb xorg-env"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(basename "$PWD") in
  libXfont-[0-9]* )
    ./configure $XORG_CONFIG --disable-devel-docs
  ;;
  libXt-[0-9]* )
    ./configure $XORG_CONFIG \
                --with-appdefaultdir=/etc/X11/app-defaults
  ;;
  * )
    ./configure $XORG_CONFIG
  ;;
esac
make

make DESTDIR=${FAKEROOT} install

if [ "$XORG_PREFIX" != "/usr" ]; then
    ln -sv $XORG_PREFIX/lib/X11 ${FAKEROOT}/usr/lib/X11
    ln -sv $XORG_PREFIX/include/X11 ${FAKEROOT}/usr/include/X11
fi

#################
} # END OF FILE #
#################

