#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/proto/bigreqsproto-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/compositeproto-0.4.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/damageproto-1.2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/dmxproto-2.3.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/dri2proto-2.8.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/dri3proto-1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/fixesproto-5.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/fontsproto-2.1.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/glproto-1.4.17.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/inputproto-2.3.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/kbproto-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/presentproto-1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/randrproto-1.4.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/recordproto-1.14.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/renderproto-0.11.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/resourceproto-1.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/scrnsaverproto-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xcmiscproto-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xextproto-7.3.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xf86bigfontproto-1.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xf86dgaproto-2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xf86driproto-2.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xf86vidmodeproto-2.3.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xineramaproto-1.2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.26.tar.bz2"
MD5SUMLIST="1a05fb01fa1d5198894c931cf925c025
            98482f65ba1e74a08bf5b056a4031ef0
            998e5904764b82642cc63d97b4ba9e95
            4ee175bbd44d05c34d43bb129be5098a
            b2721d5d24c04d9980a0c6540cb5396a
            a3d2cbe60a9ca1bf3aea6c93c817fee3
            e7431ab84d37b2678af71e29355e101d
            36934d00b00555eaacde9f091f392f97
            5565f1b0facf4a59c2778229c1f70d10
            6caebead4b779ba031727f66a7ffa358
            677ea8523eec6caca86121ad2dca0b71
            2d569c75884455c7148d133d341e8fd6
            ce4d0b05675968e4c83e003cc809660d
            1b4e5dede5ea51906f1530ca1e21d216
            a914ccc1de66ddeb4b611c6b0686e274
            cfdb57dae221b71b2703f8e2980eaaf4
            edd8a73775e8ece1d69515dd17767bfb
            e658641595327d3990eab70fdb55ca8b
            5f4847c78e41b801982c8a5e06365b24
            70c90f313b4b0851758ef77b95019584
            120e226ede5a4687b25dd357cc9b8efe
            a036dc2fcbf052ec10621fd48b68dbb1
            1d716d0dac3b664e5ee20c69d34bc10e
            e793ecefeaecfeabd1aed6a01095174e
            9959fe0bfb22a0e7260433b8d199590a
            4dc2464bfeade23dab5de38da0f6b1b5"
REQUIRES="util-macros xorg-env"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

