#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/archive/individual/data/xbitmaps-1.1.1.tar.bz2"
MD5SUMLIST="7444bbbd999b53bec6a60608a5301f4c"
REQUIRES="util-macros xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

