#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/app/xclock-1.0.7.tar.bz2"
MD5SUMLIST="6f150d063b20d08030b98c45b9bee7af"
REQUIRES="x7lib xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

