#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://archive.xfce.org/src/xfce/xfce4-session/4.10/xfce4-session-4.10.1.tar.bz2"
MD5SUMLIST="1757657c1d590aa6274b7b7cbba33352"
REQUIRES="libwnck2 libxfce4ui which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --disable-legacy-sm
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

