#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://archive.xfce.org/src/xfce/xfdesktop/4.10/xfdesktop-4.10.2.tar.bz2"
MD5SUMLIST="54a84ce63046c279fc3ec3f436d2f1b0"
REQUIRES="exo libwnck2 libxfce4ui"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

