#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.bz2"
MD5SUMLIST="c90a47c774e0963581c1ba57235f64f4"
REQUIRES="docbook docbook-xsl libxslt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

