#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="libXau libXdmcp libxcb mesalib twm util-macros x7app x7driver x7font x7lib x7proto xbitmaps xcb-proto xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm xclock xcursor-themes xinit xkeyboard-config xorg-server xterm"
TAGS="group"

