#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/archive/individual/xserver/xorg-server-1.16.0.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/xorg-server-1.16.0-add_prime_support-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/xorg-server-1.16.0-upstream_glamor_fix-1.patch"
MD5SUMLIST="8a9ff6ee9907360f09b5bdabb8089502
            ab5fec928cdd65b101e7de63ec8b17bf
            e6bb1891368757356880b909faabc5cf"
REQUIRES="libepoxy openssl pixman x7font xkeyboard-config xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../xorg-server-1.16.0-upstream_glamor_fix-1.patch

patch -Np1 -i ../xorg-server-1.16.0-add_prime_support-1.patch

./configure $XORG_CONFIG                    \
           --with-xkb-output=/var/lib/xkb   \
           --enable-dmx                     \
           --enable-glamor                  \
           --enable-install-setuid          \
           --enable-suid-wrapper
make

make DESTDIR=${FAKEROOT} install
mkdir -pv ${FAKEROOT}/etc/X11/xorg.conf.d
cat >> ${FAKEROOT}/etc/sysconfig/createfiles << "EOF"
/tmp/.ICE-unix dir 1777 root root
/tmp/.X11-unix dir 1777 root root
EOF

#################
} # END OF FILE #
#################

